//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.COND805 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap {
        
        // CODEGEN: 消息部分命名空间 http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES 以后生成的消息协定与默认值(http://tempuri.org/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_805_Orchestration_Inbound/Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Root")]
        Oncontrol3.Web.COND805.Operation_1Response Operation_1(Oncontrol3.Web.COND805.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.INPUT.Z2FM_COND_QUERY")]
    public partial class Root : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RootIT_FILTER_KEY[] iT_FILTER_KEYField;
        
        private RootIT_SELECTION_PARAMETERS[] iT_SELECTION_PARAMETERSField;
        
        private string iV_MAX_ROWSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_FILTER_KEY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RootIT_FILTER_KEY[] IT_FILTER_KEY {
            get {
                return this.iT_FILTER_KEYField;
            }
            set {
                this.iT_FILTER_KEYField = value;
                this.RaisePropertyChanged("IT_FILTER_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_SELECTION_PARAMETERS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RootIT_SELECTION_PARAMETERS[] IT_SELECTION_PARAMETERS {
            get {
                return this.iT_SELECTION_PARAMETERSField;
            }
            set {
                this.iT_SELECTION_PARAMETERSField = value;
                this.RaisePropertyChanged("IT_SELECTION_PARAMETERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_MAX_ROWS {
            get {
                return this.iV_MAX_ROWSField;
            }
            set {
                this.iV_MAX_ROWSField = value;
                this.RaisePropertyChanged("IV_MAX_ROWS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.INPUT.Z2FM_COND_QUERY")]
    public partial class RootIT_FILTER_KEY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] kEYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.INPUT.Z2FM_COND_QUERY")]
    public partial class RootIT_SELECTION_PARAMETERS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTTRIBUTE_NAMEField;
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ATTRIBUTE_NAME {
            get {
                return this.aTTRIBUTE_NAMEField;
            }
            set {
                this.aTTRIBUTE_NAMEField = value;
                this.RaisePropertyChanged("ATTRIBUTE_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
                this.RaisePropertyChanged("OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOW {
            get {
                return this.lOWField;
            }
            set {
                this.lOWField = value;
                this.RaisePropertyChanged("LOW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string HIGH {
            get {
                return this.hIGHField;
            }
            set {
                this.hIGHField = value;
                this.RaisePropertyChanged("HIGH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class Root1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RootET_MESSAGE[] eT_MESSAGEField;
        
        private RootET_COND_HEADER[] eT_COND_HEADERField;
        
        private RootET_COND_DAD[] eT_COND_DADField;
        
        private RootET_COND_DOC[] eT_COND_DOCField;
        
        private RootET_COND_FDT[] eT_COND_FDTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_MESSAGE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RootET_MESSAGE[] ET_MESSAGE {
            get {
                return this.eT_MESSAGEField;
            }
            set {
                this.eT_MESSAGEField = value;
                this.RaisePropertyChanged("ET_MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_COND_HEADER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RootET_COND_HEADER[] ET_COND_HEADER {
            get {
                return this.eT_COND_HEADERField;
            }
            set {
                this.eT_COND_HEADERField = value;
                this.RaisePropertyChanged("ET_COND_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_COND_DAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RootET_COND_DAD[] ET_COND_DAD {
            get {
                return this.eT_COND_DADField;
            }
            set {
                this.eT_COND_DADField = value;
                this.RaisePropertyChanged("ET_COND_DAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_COND_DOC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public RootET_COND_DOC[] ET_COND_DOC {
            get {
                return this.eT_COND_DOCField;
            }
            set {
                this.eT_COND_DOCField = value;
                this.RaisePropertyChanged("ET_COND_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_COND_FDT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public RootET_COND_FDT[] ET_COND_FDT {
            get {
                return this.eT_COND_FDTField;
            }
            set {
                this.eT_COND_FDTField = value;
                this.RaisePropertyChanged("ET_COND_FDT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class RootET_MESSAGE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class RootET_COND_HEADER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string cONDITION_IDField;
        
        private string cOND_DESCRField;
        
        private string cONDITION_TYPEField;
        
        private string cONDITION_ORIGINField;
        
        private string gENERATE_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CONDITION_ID {
            get {
                return this.cONDITION_IDField;
            }
            set {
                this.cONDITION_IDField = value;
                this.RaisePropertyChanged("CONDITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string COND_DESCR {
            get {
                return this.cOND_DESCRField;
            }
            set {
                this.cOND_DESCRField = value;
                this.RaisePropertyChanged("COND_DESCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONDITION_TYPE {
            get {
                return this.cONDITION_TYPEField;
            }
            set {
                this.cONDITION_TYPEField = value;
                this.RaisePropertyChanged("CONDITION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CONDITION_ORIGIN {
            get {
                return this.cONDITION_ORIGINField;
            }
            set {
                this.cONDITION_ORIGINField = value;
                this.RaisePropertyChanged("CONDITION_ORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string GENERATE_CODE {
            get {
                return this.gENERATE_CODEField;
            }
            set {
                this.gENERATE_CODEField = value;
                this.RaisePropertyChanged("GENERATE_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class RootET_COND_DAD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string dADField;
        
        private string dOBJ_DESCRIPTIONField;
        
        private string dEC_TAB_POSField;
        
        private string iNPUT_REQUIREDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DAD {
            get {
                return this.dADField;
            }
            set {
                this.dADField = value;
                this.RaisePropertyChanged("DAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOBJ_DESCRIPTION {
            get {
                return this.dOBJ_DESCRIPTIONField;
            }
            set {
                this.dOBJ_DESCRIPTIONField = value;
                this.RaisePropertyChanged("DOBJ_DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DEC_TAB_POS {
            get {
                return this.dEC_TAB_POSField;
            }
            set {
                this.dEC_TAB_POSField = value;
                this.RaisePropertyChanged("DEC_TAB_POS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string INPUT_REQUIRED {
            get {
                return this.iNPUT_REQUIREDField;
            }
            set {
                this.iNPUT_REQUIREDField = value;
                this.RaisePropertyChanged("INPUT_REQUIRED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class RootET_COND_DOC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string lANGUField;
        
        private string dOCUMENTATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LANGU {
            get {
                return this.lANGUField;
            }
            set {
                this.lANGUField = value;
                this.RaisePropertyChanged("LANGU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOCUMENTATION {
            get {
                return this.dOCUMENTATIONField;
            }
            set {
                this.dOCUMENTATIONField = value;
                this.RaisePropertyChanged("DOCUMENTATION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
    public partial class RootET_COND_FDT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string cOL_NOField;
        
        private string rOW_NOField;
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string r_LOW_VALUEField;
        
        private string r_HIGH_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string COL_NO {
            get {
                return this.cOL_NOField;
            }
            set {
                this.cOL_NOField = value;
                this.RaisePropertyChanged("COL_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ROW_NO {
            get {
                return this.rOW_NOField;
            }
            set {
                this.rOW_NOField = value;
                this.RaisePropertyChanged("ROW_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
                this.RaisePropertyChanged("OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string R_LOW_VALUE {
            get {
                return this.r_LOW_VALUEField;
            }
            set {
                this.r_LOW_VALUEField = value;
                this.RaisePropertyChanged("R_LOW_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string R_HIGH_VALUE {
            get {
                return this.r_HIGH_VALUEField;
            }
            set {
                this.r_HIGH_VALUEField = value;
                this.RaisePropertyChanged("R_HIGH_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.INPUT.Z2FM_COND_QUERY", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.INPUT.Z2FM_COND_QUERY")]
        public Oncontrol3.Web.COND805.Root Root;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(Oncontrol3.Web.COND805.Root Root) {
            this.Root = Root;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_805.Schemas.OUTPUT.Z2FM_COND_QUERY_RES")]
        public Oncontrol3.Web.COND805.Root1 Root;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(Oncontrol3.Web.COND805.Root1 Root) {
            this.Root = Root;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapChannel : Oncontrol3.Web.COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap>, Oncontrol3.Web.COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.COND805.Operation_1Response Oncontrol3.Web.COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap.Operation_1(Oncontrol3.Web.COND805.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public Oncontrol3.Web.COND805.Root1 Operation_1(Oncontrol3.Web.COND805.Root Root) {
            Oncontrol3.Web.COND805.Operation_1Request inValue = new Oncontrol3.Web.COND805.Operation_1Request();
            inValue.Root = Root;
            Oncontrol3.Web.COND805.Operation_1Response retVal = ((Oncontrol3.Web.COND805.BizTalk_RFC_TM_CRM_805_Orchestration_InboundSoap)(this)).Operation_1(inValue);
            return retVal.Root;
        }
    }
}
