//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aim.Portal.ServicesProvider.QuartzService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuartzService.IServiceBus")]
    public interface IServiceBus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/DoWork", ReplyAction="http://tempuri.org/IServiceBus/DoWorkResponse")]
        void DoWork(string key, string[] paramss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/getDllTable", ReplyAction="http://tempuri.org/IServiceBus/getDllTableResponse")]
        System.Data.DataTable getDllTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/StopKey", ReplyAction="http://tempuri.org/IServiceBus/StopKeyResponse")]
        bool StopKey(string jobkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/StartKey", ReplyAction="http://tempuri.org/IServiceBus/StartKeyResponse")]
        bool StartKey(string jobkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/Operating", ReplyAction="http://tempuri.org/IServiceBus/OperatingResponse")]
        bool Operating(string jobkey, string[] paramss);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/RefreshTask", ReplyAction="http://tempuri.org/IServiceBus/RefreshTaskResponse")]
        bool RefreshTask(string jobkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/AddNewTask", ReplyAction="http://tempuri.org/IServiceBus/AddNewTaskResponse")]
        bool AddNewTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBus/ReStart", ReplyAction="http://tempuri.org/IServiceBus/ReStartResponse")]
        bool ReStart(string jobkey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBusChannel : Aim.Portal.ServicesProvider.QuartzService.IServiceBus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBusClient : System.ServiceModel.ClientBase<Aim.Portal.ServicesProvider.QuartzService.IServiceBus>, Aim.Portal.ServicesProvider.QuartzService.IServiceBus {
        
        public ServiceBusClient() {
        }
        
        public ServiceBusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork(string key, string[] paramss) {
            base.Channel.DoWork(key, paramss);
        }
        
        public System.Data.DataTable getDllTable() {
            return base.Channel.getDllTable();
        }
        
        public bool StopKey(string jobkey) {
            return base.Channel.StopKey(jobkey);
        }
        
        public bool StartKey(string jobkey) {
            return base.Channel.StartKey(jobkey);
        }
        
        public bool Operating(string jobkey, string[] paramss) {
            return base.Channel.Operating(jobkey, paramss);
        }
        
        public bool RefreshTask(string jobkey) {
            return base.Channel.RefreshTask(jobkey);
        }
        
        public bool AddNewTask() {
            return base.Channel.AddNewTask();
        }
        
        public bool ReStart(string jobkey) {
            return base.Channel.ReStart(jobkey);
        }
    }
}
