// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class md_changeCustomerAttentionProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_changeCustomerAttentionProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202008050336368_md_changeCustomerAttentionProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
