// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class md_MarketActs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_MarketActs));
        
        string IMigrationMetadata.Id
        {
            get { return "202008130321296_md_MarketActs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
