// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class md_recustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_recustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "202008010029248_md_recustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
