// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class md_changecompanylength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(md_changecompanylength));
        
        string IMigrationMetadata.Id
        {
            get { return "202008070140449_md_changecompanylength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
