//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8825
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace FLDocService {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocServiceHttpBinding", Namespace="http://localhost/services/DocService")]
    public partial class DocService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback createDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocOperationCompleted;
        
        /// <remarks/>
        public DocService() {
            this.Url = "http://172.20.70.240:8088/services/DocService";
        }
        
        /// <remarks/>
        public event deleteDocCompletedEventHandler deleteDocCompleted;
        
        /// <remarks/>
        public event getListCompletedEventHandler getListCompleted;
        
        /// <remarks/>
        public event getDocCountCompletedEventHandler getDocCountCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event updateDocCompletedEventHandler updateDocCompleted;
        
        /// <remarks/>
        public event createDocCompletedEventHandler createDocCompleted;
        
        /// <remarks/>
        public event getDocCompletedEventHandler getDocCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.deleteDoc", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public int deleteDoc(int in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("deleteDoc", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteDoc(int in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteDoc", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EnddeleteDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteDocAsync(int in0, string in1) {
            this.deleteDocAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void deleteDocAsync(int in0, string in1, object userState) {
            if ((this.deleteDocOperationCompleted == null)) {
                this.deleteDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteDocOperationCompleted);
            }
            this.InvokeAsync("deleteDoc", new object[] {
                        in0,
                        in1}, this.deleteDocOperationCompleted, userState);
        }
        
        private void OndeleteDocOperationCompleted(object arg) {
            if ((this.deleteDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteDocCompleted(this, new deleteDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.getList", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://webservices.docs.weaver")]
        public DocInfo[] getList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, int in1, int in2) {
            object[] results = this.Invoke("getList", new object[] {
                        in0,
                        in1,
                        in2});
            return ((DocInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetList(string in0, int in1, int in2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getList", new object[] {
                        in0,
                        in1,
                        in2}, callback, asyncState);
        }
        
        /// <remarks/>
        public DocInfo[] EndgetList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DocInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getListAsync(string in0, int in1, int in2) {
            this.getListAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getListAsync(string in0, int in1, int in2, object userState) {
            if ((this.getListOperationCompleted == null)) {
                this.getListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListOperationCompleted);
            }
            this.InvokeAsync("getList", new object[] {
                        in0,
                        in1,
                        in2}, this.getListOperationCompleted, userState);
        }
        
        private void OngetListOperationCompleted(object arg) {
            if ((this.getListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListCompleted(this, new getListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.getDocCount", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public int getDocCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("getDocCount", new object[] {
                        in0});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDocCount(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDocCount", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndgetDocCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getDocCountAsync(string in0) {
            this.getDocCountAsync(in0, null);
        }
        
        /// <remarks/>
        public void getDocCountAsync(string in0, object userState) {
            if ((this.getDocCountOperationCompleted == null)) {
                this.getDocCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocCountOperationCompleted);
            }
            this.InvokeAsync("getDocCount", new object[] {
                        in0}, this.getDocCountOperationCompleted, userState);
        }
        
        private void OngetDocCountOperationCompleted(object arg) {
            if ((this.getDocCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocCountCompleted(this, new getDocCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.login", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, int in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("login", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string in0, string in1, int in2, string in3, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string in0, string in1, int in2, string in3) {
            this.loginAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void loginAsync(string in0, string in1, int in2, string in3, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.updateDoc", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public int updateDoc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DocInfo in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("updateDoc", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateDoc(DocInfo in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateDoc", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndupdateDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void updateDocAsync(DocInfo in0, string in1) {
            this.updateDocAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void updateDocAsync(DocInfo in0, string in1, object userState) {
            if ((this.updateDocOperationCompleted == null)) {
                this.updateDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDocOperationCompleted);
            }
            this.InvokeAsync("updateDoc", new object[] {
                        in0,
                        in1}, this.updateDocOperationCompleted, userState);
        }
        
        private void OnupdateDocOperationCompleted(object arg) {
            if ((this.updateDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDocCompleted(this, new updateDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.createDoc", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public int createDoc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DocInfo in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("createDoc", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateDoc(DocInfo in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createDoc", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndcreateDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createDocAsync(DocInfo in0, string in1) {
            this.createDocAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void createDocAsync(DocInfo in0, string in1, object userState) {
            if ((this.createDocOperationCompleted == null)) {
                this.createDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateDocOperationCompleted);
            }
            this.InvokeAsync("createDoc", new object[] {
                        in0,
                        in1}, this.createDocOperationCompleted, userState);
        }
        
        private void OncreateDocOperationCompleted(object arg) {
            if ((this.createDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createDocCompleted(this, new createDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:weaver.docs.webservices.DocService.getDoc", RequestNamespace="http://localhost/services/DocService", ResponseNamespace="http://localhost/services/DocService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public DocInfo getDoc(int in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("getDoc", new object[] {
                        in0,
                        in1});
            return ((DocInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDoc(int in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDoc", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public DocInfo EndgetDoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DocInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getDocAsync(int in0, string in1) {
            this.getDocAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getDocAsync(int in0, string in1, object userState) {
            if ((this.getDocOperationCompleted == null)) {
                this.getDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocOperationCompleted);
            }
            this.InvokeAsync("getDoc", new object[] {
                        in0,
                        in1}, this.getDocOperationCompleted, userState);
        }
        
        private void OngetDocOperationCompleted(object arg) {
            if ((this.getDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocCompleted(this, new getDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.docs.weaver")]
    public partial class DocInfo {
        
        private int accessorycountField;
        
        private bool accessorycountFieldSpecified;
        
        private string allParentNameField;
        
        private int assetidField;
        
        private bool assetidFieldSpecified;
        
        private DocAttachment[] attachmentsField;
        
        private int[] childdocField;
        
        private string[] chiledocnameField;
        
        private int crmidField;
        
        private bool crmidFieldSpecified;
        
        private string docCodeField;
        
        private int docEditionField;
        
        private bool docEditionFieldSpecified;
        
        private int docEditionIdField;
        
        private bool docEditionIdFieldSpecified;
        
        private string docEditionStrField;
        
        private int docPublishTypeField;
        
        private bool docPublishTypeFieldSpecified;
        
        private int docStatusField;
        
        private bool docStatusFieldSpecified;
        
        private string docStatusStrField;
        
        private string docSubjectField;
        
        private int docTypeField;
        
        private bool docTypeFieldSpecified;
        
        private string docapprovedateField;
        
        private string docapprovetimeField;
        
        private int docapproveuseridField;
        
        private bool docapproveuseridFieldSpecified;
        
        private string docapproveusernameField;
        
        private int docapproveusertypeField;
        
        private bool docapproveusertypeFieldSpecified;
        
        private string docarchivedateField;
        
        private string docarchivetimeField;
        
        private int docarchiveuseridField;
        
        private bool docarchiveuseridFieldSpecified;
        
        private string docarchiveusernameField;
        
        private int docarchiveusertypeField;
        
        private bool docarchiveusertypeFieldSpecified;
        
        private string doccanceldateField;
        
        private string doccanceltimeField;
        
        private int doccanceluseridField;
        
        private bool doccanceluseridFieldSpecified;
        
        private string doccancelusernameField;
        
        private int doccancelusertypeField;
        
        private bool doccancelusertypeFieldSpecified;
        
        private string doccontentField;
        
        private string doccreatedateField;
        
        private int doccreateridField;
        
        private bool doccreateridFieldSpecified;
        
        private string doccreaternameField;
        
        private int doccreatertypeField;
        
        private bool doccreatertypeFieldSpecified;
        
        private string doccreatetimeField;
        
        private DocCustomField[] doccustomfieldsField;
        
        private string docdepartmentStrField;
        
        private int docdepartmentidField;
        
        private bool docdepartmentidFieldSpecified;
        
        private string docinvaldateField;
        
        private string docinvaltimeField;
        
        private int docinvaluseridField;
        
        private bool docinvaluseridFieldSpecified;
        
        private string docinvalusernameField;
        
        private int docinvalusertypeField;
        
        private bool docinvalusertypeFieldSpecified;
        
        private int doclangurageField;
        
        private bool doclangurageFieldSpecified;
        
        private string doclangurageStrField;
        
        private string doclastmoddateField;
        
        private string doclastmodtimeField;
        
        private int doclastmoduseridField;
        
        private bool doclastmoduseridFieldSpecified;
        
        private string doclastmodusernameField;
        
        private int doclastmodusertypeField;
        
        private bool doclastmodusertypeFieldSpecified;
        
        private int[] dummyIdsField;
        
        private string[] dummyNamesField;
        
        private int financeidField;
        
        private bool financeidFieldSpecified;
        
        private int hrmresidField;
        
        private bool hrmresidFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int imagefileIdField;
        
        private bool imagefileIdFieldSpecified;
        
        private string invalidationdateField;
        
        private string isreplyField;
        
        private int itemidField;
        
        private bool itemidFieldSpecified;
        
        private string keywordField;
        
        private int maincategoryField;
        
        private bool maincategoryFieldSpecified;
        
        private string maincategoryStrField;
        
        private int maindocField;
        
        private bool maindocFieldSpecified;
        
        private string maindocnameField;
        
        private int owneridField;
        
        private bool owneridFieldSpecified;
        
        private string ownernameField;
        
        private int ownertypeField;
        
        private bool ownertypeFieldSpecified;
        
        private string parentidsField;
        
        private DocAttachment[] picturesField;
        
        private int projectidField;
        
        private bool projectidFieldSpecified;
        
        private string publishableField;
        
        private int replaydoccountField;
        
        private bool replaydoccountFieldSpecified;
        
        private int replydocidField;
        
        private bool replydocidFieldSpecified;
        
        private int seccategoryField;
        
        private bool seccategoryFieldSpecified;
        
        private string seccategoryStrField;
        
        private int subcategoryField;
        
        private bool subcategoryFieldSpecified;
        
        private string subcategoryStrField;
        
        private int versionIdField;
        
        private bool versionIdFieldSpecified;
        
        /// <remarks/>
        public int accessorycount {
            get {
                return this.accessorycountField;
            }
            set {
                this.accessorycountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessorycountSpecified {
            get {
                return this.accessorycountFieldSpecified;
            }
            set {
                this.accessorycountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string allParentName {
            get {
                return this.allParentNameField;
            }
            set {
                this.allParentNameField = value;
            }
        }
        
        /// <remarks/>
        public int assetid {
            get {
                return this.assetidField;
            }
            set {
                this.assetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assetidSpecified {
            get {
                return this.assetidFieldSpecified;
            }
            set {
                this.assetidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DocAttachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost/services/DocService", IsNullable=false)]
        public int[] childdoc {
            get {
                return this.childdocField;
            }
            set {
                this.childdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost/services/DocService")]
        public string[] chiledocname {
            get {
                return this.chiledocnameField;
            }
            set {
                this.chiledocnameField = value;
            }
        }
        
        /// <remarks/>
        public int crmid {
            get {
                return this.crmidField;
            }
            set {
                this.crmidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crmidSpecified {
            get {
                return this.crmidFieldSpecified;
            }
            set {
                this.crmidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docCode {
            get {
                return this.docCodeField;
            }
            set {
                this.docCodeField = value;
            }
        }
        
        /// <remarks/>
        public int docEdition {
            get {
                return this.docEditionField;
            }
            set {
                this.docEditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docEditionSpecified {
            get {
                return this.docEditionFieldSpecified;
            }
            set {
                this.docEditionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int docEditionId {
            get {
                return this.docEditionIdField;
            }
            set {
                this.docEditionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docEditionIdSpecified {
            get {
                return this.docEditionIdFieldSpecified;
            }
            set {
                this.docEditionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docEditionStr {
            get {
                return this.docEditionStrField;
            }
            set {
                this.docEditionStrField = value;
            }
        }
        
        /// <remarks/>
        public int docPublishType {
            get {
                return this.docPublishTypeField;
            }
            set {
                this.docPublishTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docPublishTypeSpecified {
            get {
                return this.docPublishTypeFieldSpecified;
            }
            set {
                this.docPublishTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int docStatus {
            get {
                return this.docStatusField;
            }
            set {
                this.docStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docStatusSpecified {
            get {
                return this.docStatusFieldSpecified;
            }
            set {
                this.docStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docStatusStr {
            get {
                return this.docStatusStrField;
            }
            set {
                this.docStatusStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docSubject {
            get {
                return this.docSubjectField;
            }
            set {
                this.docSubjectField = value;
            }
        }
        
        /// <remarks/>
        public int docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docTypeSpecified {
            get {
                return this.docTypeFieldSpecified;
            }
            set {
                this.docTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docapprovedate {
            get {
                return this.docapprovedateField;
            }
            set {
                this.docapprovedateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docapprovetime {
            get {
                return this.docapprovetimeField;
            }
            set {
                this.docapprovetimeField = value;
            }
        }
        
        /// <remarks/>
        public int docapproveuserid {
            get {
                return this.docapproveuseridField;
            }
            set {
                this.docapproveuseridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docapproveuseridSpecified {
            get {
                return this.docapproveuseridFieldSpecified;
            }
            set {
                this.docapproveuseridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docapproveusername {
            get {
                return this.docapproveusernameField;
            }
            set {
                this.docapproveusernameField = value;
            }
        }
        
        /// <remarks/>
        public int docapproveusertype {
            get {
                return this.docapproveusertypeField;
            }
            set {
                this.docapproveusertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docapproveusertypeSpecified {
            get {
                return this.docapproveusertypeFieldSpecified;
            }
            set {
                this.docapproveusertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docarchivedate {
            get {
                return this.docarchivedateField;
            }
            set {
                this.docarchivedateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docarchivetime {
            get {
                return this.docarchivetimeField;
            }
            set {
                this.docarchivetimeField = value;
            }
        }
        
        /// <remarks/>
        public int docarchiveuserid {
            get {
                return this.docarchiveuseridField;
            }
            set {
                this.docarchiveuseridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docarchiveuseridSpecified {
            get {
                return this.docarchiveuseridFieldSpecified;
            }
            set {
                this.docarchiveuseridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docarchiveusername {
            get {
                return this.docarchiveusernameField;
            }
            set {
                this.docarchiveusernameField = value;
            }
        }
        
        /// <remarks/>
        public int docarchiveusertype {
            get {
                return this.docarchiveusertypeField;
            }
            set {
                this.docarchiveusertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docarchiveusertypeSpecified {
            get {
                return this.docarchiveusertypeFieldSpecified;
            }
            set {
                this.docarchiveusertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccanceldate {
            get {
                return this.doccanceldateField;
            }
            set {
                this.doccanceldateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccanceltime {
            get {
                return this.doccanceltimeField;
            }
            set {
                this.doccanceltimeField = value;
            }
        }
        
        /// <remarks/>
        public int doccanceluserid {
            get {
                return this.doccanceluseridField;
            }
            set {
                this.doccanceluseridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doccanceluseridSpecified {
            get {
                return this.doccanceluseridFieldSpecified;
            }
            set {
                this.doccanceluseridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccancelusername {
            get {
                return this.doccancelusernameField;
            }
            set {
                this.doccancelusernameField = value;
            }
        }
        
        /// <remarks/>
        public int doccancelusertype {
            get {
                return this.doccancelusertypeField;
            }
            set {
                this.doccancelusertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doccancelusertypeSpecified {
            get {
                return this.doccancelusertypeFieldSpecified;
            }
            set {
                this.doccancelusertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccontent {
            get {
                return this.doccontentField;
            }
            set {
                this.doccontentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccreatedate {
            get {
                return this.doccreatedateField;
            }
            set {
                this.doccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int doccreaterid {
            get {
                return this.doccreateridField;
            }
            set {
                this.doccreateridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doccreateridSpecified {
            get {
                return this.doccreateridFieldSpecified;
            }
            set {
                this.doccreateridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccreatername {
            get {
                return this.doccreaternameField;
            }
            set {
                this.doccreaternameField = value;
            }
        }
        
        /// <remarks/>
        public int doccreatertype {
            get {
                return this.doccreatertypeField;
            }
            set {
                this.doccreatertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doccreatertypeSpecified {
            get {
                return this.doccreatertypeFieldSpecified;
            }
            set {
                this.doccreatertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doccreatetime {
            get {
                return this.doccreatetimeField;
            }
            set {
                this.doccreatetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DocCustomField[] doccustomfields {
            get {
                return this.doccustomfieldsField;
            }
            set {
                this.doccustomfieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docdepartmentStr {
            get {
                return this.docdepartmentStrField;
            }
            set {
                this.docdepartmentStrField = value;
            }
        }
        
        /// <remarks/>
        public int docdepartmentid {
            get {
                return this.docdepartmentidField;
            }
            set {
                this.docdepartmentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docdepartmentidSpecified {
            get {
                return this.docdepartmentidFieldSpecified;
            }
            set {
                this.docdepartmentidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docinvaldate {
            get {
                return this.docinvaldateField;
            }
            set {
                this.docinvaldateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docinvaltime {
            get {
                return this.docinvaltimeField;
            }
            set {
                this.docinvaltimeField = value;
            }
        }
        
        /// <remarks/>
        public int docinvaluserid {
            get {
                return this.docinvaluseridField;
            }
            set {
                this.docinvaluseridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docinvaluseridSpecified {
            get {
                return this.docinvaluseridFieldSpecified;
            }
            set {
                this.docinvaluseridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docinvalusername {
            get {
                return this.docinvalusernameField;
            }
            set {
                this.docinvalusernameField = value;
            }
        }
        
        /// <remarks/>
        public int docinvalusertype {
            get {
                return this.docinvalusertypeField;
            }
            set {
                this.docinvalusertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docinvalusertypeSpecified {
            get {
                return this.docinvalusertypeFieldSpecified;
            }
            set {
                this.docinvalusertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int doclangurage {
            get {
                return this.doclangurageField;
            }
            set {
                this.doclangurageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doclangurageSpecified {
            get {
                return this.doclangurageFieldSpecified;
            }
            set {
                this.doclangurageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doclangurageStr {
            get {
                return this.doclangurageStrField;
            }
            set {
                this.doclangurageStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doclastmoddate {
            get {
                return this.doclastmoddateField;
            }
            set {
                this.doclastmoddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doclastmodtime {
            get {
                return this.doclastmodtimeField;
            }
            set {
                this.doclastmodtimeField = value;
            }
        }
        
        /// <remarks/>
        public int doclastmoduserid {
            get {
                return this.doclastmoduseridField;
            }
            set {
                this.doclastmoduseridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doclastmoduseridSpecified {
            get {
                return this.doclastmoduseridFieldSpecified;
            }
            set {
                this.doclastmoduseridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doclastmodusername {
            get {
                return this.doclastmodusernameField;
            }
            set {
                this.doclastmodusernameField = value;
            }
        }
        
        /// <remarks/>
        public int doclastmodusertype {
            get {
                return this.doclastmodusertypeField;
            }
            set {
                this.doclastmodusertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doclastmodusertypeSpecified {
            get {
                return this.doclastmodusertypeFieldSpecified;
            }
            set {
                this.doclastmodusertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost/services/DocService", IsNullable=false)]
        public int[] dummyIds {
            get {
                return this.dummyIdsField;
            }
            set {
                this.dummyIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://localhost/services/DocService")]
        public string[] dummyNames {
            get {
                return this.dummyNamesField;
            }
            set {
                this.dummyNamesField = value;
            }
        }
        
        /// <remarks/>
        public int financeid {
            get {
                return this.financeidField;
            }
            set {
                this.financeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financeidSpecified {
            get {
                return this.financeidFieldSpecified;
            }
            set {
                this.financeidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int hrmresid {
            get {
                return this.hrmresidField;
            }
            set {
                this.hrmresidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hrmresidSpecified {
            get {
                return this.hrmresidFieldSpecified;
            }
            set {
                this.hrmresidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int imagefileId {
            get {
                return this.imagefileIdField;
            }
            set {
                this.imagefileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagefileIdSpecified {
            get {
                return this.imagefileIdFieldSpecified;
            }
            set {
                this.imagefileIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invalidationdate {
            get {
                return this.invalidationdateField;
            }
            set {
                this.invalidationdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isreply {
            get {
                return this.isreplyField;
            }
            set {
                this.isreplyField = value;
            }
        }
        
        /// <remarks/>
        public int itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemidSpecified {
            get {
                return this.itemidFieldSpecified;
            }
            set {
                this.itemidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        public int maincategory {
            get {
                return this.maincategoryField;
            }
            set {
                this.maincategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maincategorySpecified {
            get {
                return this.maincategoryFieldSpecified;
            }
            set {
                this.maincategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maincategoryStr {
            get {
                return this.maincategoryStrField;
            }
            set {
                this.maincategoryStrField = value;
            }
        }
        
        /// <remarks/>
        public int maindoc {
            get {
                return this.maindocField;
            }
            set {
                this.maindocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maindocSpecified {
            get {
                return this.maindocFieldSpecified;
            }
            set {
                this.maindocFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maindocname {
            get {
                return this.maindocnameField;
            }
            set {
                this.maindocnameField = value;
            }
        }
        
        /// <remarks/>
        public int ownerid {
            get {
                return this.owneridField;
            }
            set {
                this.owneridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool owneridSpecified {
            get {
                return this.owneridFieldSpecified;
            }
            set {
                this.owneridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ownername {
            get {
                return this.ownernameField;
            }
            set {
                this.ownernameField = value;
            }
        }
        
        /// <remarks/>
        public int ownertype {
            get {
                return this.ownertypeField;
            }
            set {
                this.ownertypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownertypeSpecified {
            get {
                return this.ownertypeFieldSpecified;
            }
            set {
                this.ownertypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parentids {
            get {
                return this.parentidsField;
            }
            set {
                this.parentidsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DocAttachment[] pictures {
            get {
                return this.picturesField;
            }
            set {
                this.picturesField = value;
            }
        }
        
        /// <remarks/>
        public int projectid {
            get {
                return this.projectidField;
            }
            set {
                this.projectidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectidSpecified {
            get {
                return this.projectidFieldSpecified;
            }
            set {
                this.projectidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string publishable {
            get {
                return this.publishableField;
            }
            set {
                this.publishableField = value;
            }
        }
        
        /// <remarks/>
        public int replaydoccount {
            get {
                return this.replaydoccountField;
            }
            set {
                this.replaydoccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replaydoccountSpecified {
            get {
                return this.replaydoccountFieldSpecified;
            }
            set {
                this.replaydoccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int replydocid {
            get {
                return this.replydocidField;
            }
            set {
                this.replydocidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replydocidSpecified {
            get {
                return this.replydocidFieldSpecified;
            }
            set {
                this.replydocidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int seccategory {
            get {
                return this.seccategoryField;
            }
            set {
                this.seccategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seccategorySpecified {
            get {
                return this.seccategoryFieldSpecified;
            }
            set {
                this.seccategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seccategoryStr {
            get {
                return this.seccategoryStrField;
            }
            set {
                this.seccategoryStrField = value;
            }
        }
        
        /// <remarks/>
        public int subcategory {
            get {
                return this.subcategoryField;
            }
            set {
                this.subcategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subcategorySpecified {
            get {
                return this.subcategoryFieldSpecified;
            }
            set {
                this.subcategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subcategoryStr {
            get {
                return this.subcategoryStrField;
            }
            set {
                this.subcategoryStrField = value;
            }
        }
        
        /// <remarks/>
        public int versionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionIdSpecified {
            get {
                return this.versionIdFieldSpecified;
            }
            set {
                this.versionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.docs.weaver")]
    public partial class DocAttachment {
        
        private string aesCodeField;
        
        private int docImageFileIdField;
        
        private bool docImageFileIdFieldSpecified;
        
        private string docfiletypeField;
        
        private int docidField;
        
        private bool docidFieldSpecified;
        
        private string filecontentField;
        
        private string filenameField;
        
        private string filerealpathField;
        
        private string filetypeField;
        
        private int fileusedField;
        
        private bool fileusedFieldSpecified;
        
        private string imagefiledescField;
        
        private int imagefileheightField;
        
        private bool imagefileheightFieldSpecified;
        
        private int imagefileidField;
        
        private bool imagefileidFieldSpecified;
        
        private string imagefilenameField;
        
        private int imagefilesizeField;
        
        private bool imagefilesizeFieldSpecified;
        
        private int imagefilewidthField;
        
        private bool imagefilewidthFieldSpecified;
        
        private int isAesEncrypeField;
        
        private bool isAesEncrypeFieldSpecified;
        
        private int isencrypeField;
        
        private bool isencrypeFieldSpecified;
        
        private string isextfileField;
        
        private int iszipField;
        
        private bool iszipFieldSpecified;
        
        private string versionDetailField;
        
        private int versionIdField;
        
        private bool versionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aesCode {
            get {
                return this.aesCodeField;
            }
            set {
                this.aesCodeField = value;
            }
        }
        
        /// <remarks/>
        public int docImageFileId {
            get {
                return this.docImageFileIdField;
            }
            set {
                this.docImageFileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docImageFileIdSpecified {
            get {
                return this.docImageFileIdFieldSpecified;
            }
            set {
                this.docImageFileIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docfiletype {
            get {
                return this.docfiletypeField;
            }
            set {
                this.docfiletypeField = value;
            }
        }
        
        /// <remarks/>
        public int docid {
            get {
                return this.docidField;
            }
            set {
                this.docidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docidSpecified {
            get {
                return this.docidFieldSpecified;
            }
            set {
                this.docidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filecontent {
            get {
                return this.filecontentField;
            }
            set {
                this.filecontentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filerealpath {
            get {
                return this.filerealpathField;
            }
            set {
                this.filerealpathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filetype {
            get {
                return this.filetypeField;
            }
            set {
                this.filetypeField = value;
            }
        }
        
        /// <remarks/>
        public int fileused {
            get {
                return this.fileusedField;
            }
            set {
                this.fileusedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileusedSpecified {
            get {
                return this.fileusedFieldSpecified;
            }
            set {
                this.fileusedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imagefiledesc {
            get {
                return this.imagefiledescField;
            }
            set {
                this.imagefiledescField = value;
            }
        }
        
        /// <remarks/>
        public int imagefileheight {
            get {
                return this.imagefileheightField;
            }
            set {
                this.imagefileheightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagefileheightSpecified {
            get {
                return this.imagefileheightFieldSpecified;
            }
            set {
                this.imagefileheightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int imagefileid {
            get {
                return this.imagefileidField;
            }
            set {
                this.imagefileidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagefileidSpecified {
            get {
                return this.imagefileidFieldSpecified;
            }
            set {
                this.imagefileidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imagefilename {
            get {
                return this.imagefilenameField;
            }
            set {
                this.imagefilenameField = value;
            }
        }
        
        /// <remarks/>
        public int imagefilesize {
            get {
                return this.imagefilesizeField;
            }
            set {
                this.imagefilesizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagefilesizeSpecified {
            get {
                return this.imagefilesizeFieldSpecified;
            }
            set {
                this.imagefilesizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int imagefilewidth {
            get {
                return this.imagefilewidthField;
            }
            set {
                this.imagefilewidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagefilewidthSpecified {
            get {
                return this.imagefilewidthFieldSpecified;
            }
            set {
                this.imagefilewidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int isAesEncrype {
            get {
                return this.isAesEncrypeField;
            }
            set {
                this.isAesEncrypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAesEncrypeSpecified {
            get {
                return this.isAesEncrypeFieldSpecified;
            }
            set {
                this.isAesEncrypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int isencrype {
            get {
                return this.isencrypeField;
            }
            set {
                this.isencrypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isencrypeSpecified {
            get {
                return this.isencrypeFieldSpecified;
            }
            set {
                this.isencrypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isextfile {
            get {
                return this.isextfileField;
            }
            set {
                this.isextfileField = value;
            }
        }
        
        /// <remarks/>
        public int iszip {
            get {
                return this.iszipField;
            }
            set {
                this.iszipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iszipSpecified {
            get {
                return this.iszipFieldSpecified;
            }
            set {
                this.iszipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string versionDetail {
            get {
                return this.versionDetailField;
            }
            set {
                this.versionDetailField = value;
            }
        }
        
        /// <remarks/>
        public int versionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionIdSpecified {
            get {
                return this.versionIdFieldSpecified;
            }
            set {
                this.versionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.docs.weaver")]
    public partial class DocCustomField {
        
        private string fielddbtypeField;
        
        private string fieldhtmltypeField;
        
        private int fieldidField;
        
        private bool fieldidFieldSpecified;
        
        private string fieldshowField;
        
        private int fieldtypeField;
        
        private bool fieldtypeFieldSpecified;
        
        private string fieldvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fielddbtype {
            get {
                return this.fielddbtypeField;
            }
            set {
                this.fielddbtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fieldhtmltype {
            get {
                return this.fieldhtmltypeField;
            }
            set {
                this.fieldhtmltypeField = value;
            }
        }
        
        /// <remarks/>
        public int fieldid {
            get {
                return this.fieldidField;
            }
            set {
                this.fieldidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldidSpecified {
            get {
                return this.fieldidFieldSpecified;
            }
            set {
                this.fieldidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fieldshow {
            get {
                return this.fieldshowField;
            }
            set {
                this.fieldshowField = value;
            }
        }
        
        /// <remarks/>
        public int fieldtype {
            get {
                return this.fieldtypeField;
            }
            set {
                this.fieldtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldtypeSpecified {
            get {
                return this.fieldtypeFieldSpecified;
            }
            set {
                this.fieldtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fieldvalue {
            get {
                return this.fieldvalueField;
            }
            set {
                this.fieldvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void deleteDocCompletedEventHandler(object sender, deleteDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getListCompletedEventHandler(object sender, getListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getDocCountCompletedEventHandler(object sender, getDocCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void updateDocCompletedEventHandler(object sender, updateDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void createDocCompletedEventHandler(object sender, createDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getDocCompletedEventHandler(object sender, getDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocInfo)(this.results[0]));
            }
        }
    }
}
