//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.RATE603 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap {
        
        // CODEGEN: 消息部分命名空间 http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES 以后生成的消息协定与默认值(http://tempuri.org/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_603_Orchestration_Inbound/Exec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_SQ_RATE_GET_RES")]
        Oncontrol3.Web.RATE603.ExecResponse Exec(Oncontrol3.Web.RATE603.ExecRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.INPUT.Z2FM_SQ_RATE_GET")]
    public partial class Z2FM_SQ_RATE_GET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_KEYField;
        
        private string iV_RATE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IV_KEY {
            get {
                return this.iV_KEYField;
            }
            set {
                this.iV_KEYField = value;
                this.RaisePropertyChanged("IV_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IV_RATE_ID {
            get {
                return this.iV_RATE_IDField;
            }
            set {
                this.iV_RATE_IDField = value;
                this.RaisePropertyChanged("IV_RATE_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rATE_IDField;
        
        private string kEYField;
        
        private string sEVERITYField;
        
        private string dESCRIPTIONField;
        
        private string tCUSAGECD085Field;
        
        private string tIMEZONEField;
        
        private string rATE_SPLITField;
        
        private string mULTI_CHRG_TYPEField;
        
        private string tCETField;
        
        private string vAL_INDICATORField;
        
        private string rATE_TAB_TYPEField;
        
        private string sOL_SPEND_DIMENSIONField;
        
        private string sS_SCALE_ITEM_UOMField;
        
        private string zSETTLE_ROLEField;
        
        private string zSETTLE_OBJField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEORG_DATA[] oRG_DATAField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATERATESCALE rATESCALEField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITY[] vALIDITYField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEMSG[] mSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RATE_ID {
            get {
                return this.rATE_IDField;
            }
            set {
                this.rATE_IDField = value;
                this.RaisePropertyChanged("RATE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SEVERITY {
            get {
                return this.sEVERITYField;
            }
            set {
                this.sEVERITYField = value;
                this.RaisePropertyChanged("SEVERITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TCUSAGECD085 {
            get {
                return this.tCUSAGECD085Field;
            }
            set {
                this.tCUSAGECD085Field = value;
                this.RaisePropertyChanged("TCUSAGECD085");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TIMEZONE {
            get {
                return this.tIMEZONEField;
            }
            set {
                this.tIMEZONEField = value;
                this.RaisePropertyChanged("TIMEZONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RATE_SPLIT {
            get {
                return this.rATE_SPLITField;
            }
            set {
                this.rATE_SPLITField = value;
                this.RaisePropertyChanged("RATE_SPLIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MULTI_CHRG_TYPE {
            get {
                return this.mULTI_CHRG_TYPEField;
            }
            set {
                this.mULTI_CHRG_TYPEField = value;
                this.RaisePropertyChanged("MULTI_CHRG_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TCET {
            get {
                return this.tCETField;
            }
            set {
                this.tCETField = value;
                this.RaisePropertyChanged("TCET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string VAL_INDICATOR {
            get {
                return this.vAL_INDICATORField;
            }
            set {
                this.vAL_INDICATORField = value;
                this.RaisePropertyChanged("VAL_INDICATOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RATE_TAB_TYPE {
            get {
                return this.rATE_TAB_TYPEField;
            }
            set {
                this.rATE_TAB_TYPEField = value;
                this.RaisePropertyChanged("RATE_TAB_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SOL_SPEND_DIMENSION {
            get {
                return this.sOL_SPEND_DIMENSIONField;
            }
            set {
                this.sOL_SPEND_DIMENSIONField = value;
                this.RaisePropertyChanged("SOL_SPEND_DIMENSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SS_SCALE_ITEM_UOM {
            get {
                return this.sS_SCALE_ITEM_UOMField;
            }
            set {
                this.sS_SCALE_ITEM_UOMField = value;
                this.RaisePropertyChanged("SS_SCALE_ITEM_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ZSETTLE_ROLE {
            get {
                return this.zSETTLE_ROLEField;
            }
            set {
                this.zSETTLE_ROLEField = value;
                this.RaisePropertyChanged("ZSETTLE_ROLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ZSETTLE_OBJ {
            get {
                return this.zSETTLE_OBJField;
            }
            set {
                this.zSETTLE_OBJField = value;
                this.RaisePropertyChanged("ZSETTLE_OBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORG_DATA", Order=15)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEORG_DATA[] ORG_DATA {
            get {
                return this.oRG_DATAField;
            }
            set {
                this.oRG_DATAField = value;
                this.RaisePropertyChanged("ORG_DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Z2FM_SQ_RATE_GET_RESIT_RATERATESCALE RATESCALE {
            get {
                return this.rATESCALEField;
            }
            set {
                this.rATESCALEField = value;
                this.RaisePropertyChanged("RATESCALE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VALIDITY", Order=17)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITY[] VALIDITY {
            get {
                return this.vALIDITYField;
            }
            set {
                this.vALIDITYField = value;
                this.RaisePropertyChanged("VALIDITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MSG", Order=18)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEMSG[] MSG {
            get {
                return this.mSGField;
            }
            set {
                this.mSGField = value;
                this.RaisePropertyChanged("MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEORG_DATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oRG_UNITField;
        
        private string kEYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ORG_UNIT {
            get {
                return this.oRG_UNITField;
            }
            set {
                this.oRG_UNITField = value;
                this.RaisePropertyChanged("ORG_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATERATESCALE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dIMENSION_INDXField;
        
        private string kEYField;
        
        private string cALC_BASEField;
        
        private string sCATYPField;
        
        private string sCALE_UOMField;
        
        private string sCALE_CURRField;
        
        private string rOUND_RULEField;
        
        private string cURRENCY_RELField;
        
        private string iNITVAL_SUPPORTField;
        
        private string mINVAL_SUPPORTEDField;
        
        private string mAXVAL_SUPPORTEDField;
        
        private string rEL_FOR_WGTBRKField;
        
        private string cALC_TYPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DIMENSION_INDX {
            get {
                return this.dIMENSION_INDXField;
            }
            set {
                this.dIMENSION_INDXField = value;
                this.RaisePropertyChanged("DIMENSION_INDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CALC_BASE {
            get {
                return this.cALC_BASEField;
            }
            set {
                this.cALC_BASEField = value;
                this.RaisePropertyChanged("CALC_BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SCATYP {
            get {
                return this.sCATYPField;
            }
            set {
                this.sCATYPField = value;
                this.RaisePropertyChanged("SCATYP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SCALE_UOM {
            get {
                return this.sCALE_UOMField;
            }
            set {
                this.sCALE_UOMField = value;
                this.RaisePropertyChanged("SCALE_UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SCALE_CURR {
            get {
                return this.sCALE_CURRField;
            }
            set {
                this.sCALE_CURRField = value;
                this.RaisePropertyChanged("SCALE_CURR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ROUND_RULE {
            get {
                return this.rOUND_RULEField;
            }
            set {
                this.rOUND_RULEField = value;
                this.RaisePropertyChanged("ROUND_RULE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CURRENCY_REL {
            get {
                return this.cURRENCY_RELField;
            }
            set {
                this.cURRENCY_RELField = value;
                this.RaisePropertyChanged("CURRENCY_REL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string INITVAL_SUPPORT {
            get {
                return this.iNITVAL_SUPPORTField;
            }
            set {
                this.iNITVAL_SUPPORTField = value;
                this.RaisePropertyChanged("INITVAL_SUPPORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MINVAL_SUPPORTED {
            get {
                return this.mINVAL_SUPPORTEDField;
            }
            set {
                this.mINVAL_SUPPORTEDField = value;
                this.RaisePropertyChanged("MINVAL_SUPPORTED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MAXVAL_SUPPORTED {
            get {
                return this.mAXVAL_SUPPORTEDField;
            }
            set {
                this.mAXVAL_SUPPORTEDField = value;
                this.RaisePropertyChanged("MAXVAL_SUPPORTED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string REL_FOR_WGTBRK {
            get {
                return this.rEL_FOR_WGTBRKField;
            }
            set {
                this.rEL_FOR_WGTBRKField = value;
                this.RaisePropertyChanged("REL_FOR_WGTBRK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CALC_TYP {
            get {
                return this.cALC_TYPField;
            }
            set {
                this.cALC_TYPField = value;
                this.RaisePropertyChanged("CALC_TYP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zNUMBERField;
        
        private string kEYField;
        
        private string vALID_START_DTField;
        
        private string vALID_END_DTField;
        
        private string cURRENCYField;
        
        private string dESCRIPTIONField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREF[] cALCRULEREFField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIM rATES_DIMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ZNUMBER {
            get {
                return this.zNUMBERField;
            }
            set {
                this.zNUMBERField = value;
                this.RaisePropertyChanged("ZNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VALID_START_DT {
            get {
                return this.vALID_START_DTField;
            }
            set {
                this.vALID_START_DTField = value;
                this.RaisePropertyChanged("VALID_START_DT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VALID_END_DT {
            get {
                return this.vALID_END_DTField;
            }
            set {
                this.vALID_END_DTField = value;
                this.RaisePropertyChanged("VALID_END_DT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
                this.RaisePropertyChanged("CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CALCRULEREF", Order=6)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREF[] CALCRULEREF {
            get {
                return this.cALCRULEREFField;
            }
            set {
                this.cALCRULEREFField = value;
                this.RaisePropertyChanged("CALCRULEREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIM RATES_DIM {
            get {
                return this.rATES_DIMField;
            }
            set {
                this.rATES_DIMField = value;
                this.RaisePropertyChanged("RATES_DIM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cALC_BASE_CODEField;
        
        private string kEYField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREFQUANTITY qUANTITYField;
        
        private string rOUND_RULEField;
        
        private string fOR_REL_SCLITMField;
        
        private string cALC_RULE_LEVELField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CALC_BASE_CODE {
            get {
                return this.cALC_BASE_CODEField;
            }
            set {
                this.cALC_BASE_CODEField = value;
                this.RaisePropertyChanged("CALC_BASE_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREFQUANTITY QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ROUND_RULE {
            get {
                return this.rOUND_RULEField;
            }
            set {
                this.rOUND_RULEField = value;
                this.RaisePropertyChanged("ROUND_RULE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FOR_REL_SCLITM {
            get {
                return this.fOR_REL_SCLITMField;
            }
            set {
                this.fOR_REL_SCLITMField = value;
                this.RaisePropertyChanged("FOR_REL_SCLITM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CALC_RULE_LEVEL {
            get {
                return this.cALC_RULE_LEVELField;
            }
            set {
                this.cALC_RULE_LEVELField = value;
                this.RaisePropertyChanged("CALC_RULE_LEVEL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYCALCRULEREFQUANTITY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qTY_UNIT_CField;
        
        private string qTY_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QTY_UNIT_C {
            get {
                return this.qTY_UNIT_CField;
            }
            set {
                this.qTY_UNIT_CField = value;
                this.RaisePropertyChanged("QTY_UNIT_C");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string QTY_VALUE {
            get {
                return this.qTY_VALUEField;
            }
            set {
                this.qTY_VALUEField = value;
                this.RaisePropertyChanged("QTY_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM1 sCALE_ITEM1Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM2 sCALE_ITEM2Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM3 sCALE_ITEM3Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM4 sCALE_ITEM4Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM5 sCALE_ITEM5Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM6 sCALE_ITEM6Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM7 sCALE_ITEM7Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM8 sCALE_ITEM8Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM9 sCALE_ITEM9Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM10 sCALE_ITEM10Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM11 sCALE_ITEM11Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM12 sCALE_ITEM12Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM13 sCALE_ITEM13Field;
        
        private Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM14 sCALE_ITEM14Field;
        
        private string zERO_RATEField;
        
        private string rATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM1 SCALE_ITEM1 {
            get {
                return this.sCALE_ITEM1Field;
            }
            set {
                this.sCALE_ITEM1Field = value;
                this.RaisePropertyChanged("SCALE_ITEM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM2 SCALE_ITEM2 {
            get {
                return this.sCALE_ITEM2Field;
            }
            set {
                this.sCALE_ITEM2Field = value;
                this.RaisePropertyChanged("SCALE_ITEM2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM3 SCALE_ITEM3 {
            get {
                return this.sCALE_ITEM3Field;
            }
            set {
                this.sCALE_ITEM3Field = value;
                this.RaisePropertyChanged("SCALE_ITEM3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM4 SCALE_ITEM4 {
            get {
                return this.sCALE_ITEM4Field;
            }
            set {
                this.sCALE_ITEM4Field = value;
                this.RaisePropertyChanged("SCALE_ITEM4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM5 SCALE_ITEM5 {
            get {
                return this.sCALE_ITEM5Field;
            }
            set {
                this.sCALE_ITEM5Field = value;
                this.RaisePropertyChanged("SCALE_ITEM5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM6 SCALE_ITEM6 {
            get {
                return this.sCALE_ITEM6Field;
            }
            set {
                this.sCALE_ITEM6Field = value;
                this.RaisePropertyChanged("SCALE_ITEM6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM7 SCALE_ITEM7 {
            get {
                return this.sCALE_ITEM7Field;
            }
            set {
                this.sCALE_ITEM7Field = value;
                this.RaisePropertyChanged("SCALE_ITEM7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM8 SCALE_ITEM8 {
            get {
                return this.sCALE_ITEM8Field;
            }
            set {
                this.sCALE_ITEM8Field = value;
                this.RaisePropertyChanged("SCALE_ITEM8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM9 SCALE_ITEM9 {
            get {
                return this.sCALE_ITEM9Field;
            }
            set {
                this.sCALE_ITEM9Field = value;
                this.RaisePropertyChanged("SCALE_ITEM9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM10 SCALE_ITEM10 {
            get {
                return this.sCALE_ITEM10Field;
            }
            set {
                this.sCALE_ITEM10Field = value;
                this.RaisePropertyChanged("SCALE_ITEM10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM11 SCALE_ITEM11 {
            get {
                return this.sCALE_ITEM11Field;
            }
            set {
                this.sCALE_ITEM11Field = value;
                this.RaisePropertyChanged("SCALE_ITEM11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM12 SCALE_ITEM12 {
            get {
                return this.sCALE_ITEM12Field;
            }
            set {
                this.sCALE_ITEM12Field = value;
                this.RaisePropertyChanged("SCALE_ITEM12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM13 SCALE_ITEM13 {
            get {
                return this.sCALE_ITEM13Field;
            }
            set {
                this.sCALE_ITEM13Field = value;
                this.RaisePropertyChanged("SCALE_ITEM13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM14 SCALE_ITEM14 {
            get {
                return this.sCALE_ITEM14Field;
            }
            set {
                this.sCALE_ITEM14Field = value;
                this.RaisePropertyChanged("SCALE_ITEM14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ZERO_RATE {
            get {
                return this.zERO_RATEField;
            }
            set {
                this.zERO_RATEField = value;
                this.RaisePropertyChanged("ZERO_RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
                this.RaisePropertyChanged("RATE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM6 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM7 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM8 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM9 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM10 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM11 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM12 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM13 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEVALIDITYRATES_DIMSCALE_ITEM14 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sCALE_ITEMField;
        
        private string sCALE_ITEM_RAWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SCALE_ITEM {
            get {
                return this.sCALE_ITEMField;
            }
            set {
                this.sCALE_ITEMField = value;
                this.RaisePropertyChanged("SCALE_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SCALE_ITEM_RAW {
            get {
                return this.sCALE_ITEM_RAWField;
            }
            set {
                this.sCALE_ITEM_RAWField = value;
                this.RaisePropertyChanged("SCALE_ITEM_RAW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
    public partial class Z2FM_SQ_RATE_GET_RESIT_RATEMSG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mSG_TYPEField;
        
        private string mSG_IDField;
        
        private string mSG_NOField;
        
        private string mSG_TEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MSG_TYPE {
            get {
                return this.mSG_TYPEField;
            }
            set {
                this.mSG_TYPEField = value;
                this.RaisePropertyChanged("MSG_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MSG_ID {
            get {
                return this.mSG_IDField;
            }
            set {
                this.mSG_IDField = value;
                this.RaisePropertyChanged("MSG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSG_NO {
            get {
                return this.mSG_NOField;
            }
            set {
                this.mSG_NOField = value;
                this.RaisePropertyChanged("MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MSG_TEXT {
            get {
                return this.mSG_TEXTField;
            }
            set {
                this.mSG_TEXTField = value;
                this.RaisePropertyChanged("MSG_TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Exec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.INPUT.Z2FM_SQ_RATE_GET", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.INPUT.Z2FM_SQ_RATE_GET")]
        public Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET Z2FM_SQ_RATE_GET;
        
        public ExecRequest() {
        }
        
        public ExecRequest(Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET Z2FM_SQ_RATE_GET) {
            this.Z2FM_SQ_RATE_GET = Z2FM_SQ_RATE_GET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://BizTalk.RFC.TM_CRM_603.Schemas.OUTPUT.Z2FM_SQ_RATE_GET_RES")]
        [System.Xml.Serialization.XmlArrayItemAttribute("IT_RATE", IsNullable=false)]
        public Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET_RESIT_RATE[] Z2FM_SQ_RATE_GET_RES;
        
        public ExecResponse() {
        }
        
        public ExecResponse(Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET_RESIT_RATE[] Z2FM_SQ_RATE_GET_RES) {
            this.Z2FM_SQ_RATE_GET_RES = Z2FM_SQ_RATE_GET_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapChannel : Oncontrol3.Web.RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap>, Oncontrol3.Web.RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.RATE603.ExecResponse Oncontrol3.Web.RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap.Exec(Oncontrol3.Web.RATE603.ExecRequest request) {
            return base.Channel.Exec(request);
        }
        
        public Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET_RESIT_RATE[] Exec(Oncontrol3.Web.RATE603.Z2FM_SQ_RATE_GET Z2FM_SQ_RATE_GET) {
            Oncontrol3.Web.RATE603.ExecRequest inValue = new Oncontrol3.Web.RATE603.ExecRequest();
            inValue.Z2FM_SQ_RATE_GET = Z2FM_SQ_RATE_GET;
            Oncontrol3.Web.RATE603.ExecResponse retVal = ((Oncontrol3.Web.RATE603.BizTalk_RFC_TM_CRM_603_Orchestration_InboundSoap)(this)).Exec(inValue);
            return retVal.Z2FM_SQ_RATE_GET_RES;
        }
    }
}
