//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.FWA703 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap {
        
        // CODEGEN: 消息部分命名空间 http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES 以后生成的消息协定与默认值(http://tempuri.org/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_703_Orchestration_Inbound/Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_SQ_FWA_SEARCH_RES")]
        Oncontrol3.Web.FWA703.Operation_1Response Operation_1(Oncontrol3.Web.FWA703.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.INPUT.Z2FM_SQ_FWA_SEARCH")]
    public partial class Z2FM_SQ_FWA_SEARCH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_KEYField;
        
        private string iV_FAGRMNTID044Field;
        
        private string iV_VERSION_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IV_KEY {
            get {
                return this.iV_KEYField;
            }
            set {
                this.iV_KEYField = value;
                this.RaisePropertyChanged("IV_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IV_FAGRMNTID044 {
            get {
                return this.iV_FAGRMNTID044Field;
            }
            set {
                this.iV_FAGRMNTID044Field = value;
                this.RaisePropertyChanged("IV_FAGRMNTID044");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IV_VERSION_NO {
            get {
                return this.iV_VERSION_NOField;
            }
            set {
                this.iV_VERSION_NOField = value;
                this.RaisePropertyChanged("IV_VERSION_NO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string fAGTYPEID103Field;
        
        private string fAGUSAGEID105Field;
        
        private string fAGRMNTID044Field;
        
        private string vERSION_NOField;
        
        private string eXTERNAL_FA_IDField;
        
        private string dIM_WT_PROFILEField;
        
        private string vALIDITY_STARTField;
        
        private string vALIDITY_ENDField;
        
        private string fAGPRIOID104Field;
        
        private string dOC_CURRENCYField;
        
        private string zXSYField;
        
        private string zBJLXField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAROOT_TEXT[] rOOT_TEXTField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_CONTRACTORS[] fAG_CONTRACTORSField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_PARTY[] fAG_PARTYField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEM[] fAG_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FAGTYPEID103 {
            get {
                return this.fAGTYPEID103Field;
            }
            set {
                this.fAGTYPEID103Field = value;
                this.RaisePropertyChanged("FAGTYPEID103");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FAGUSAGEID105 {
            get {
                return this.fAGUSAGEID105Field;
            }
            set {
                this.fAGUSAGEID105Field = value;
                this.RaisePropertyChanged("FAGUSAGEID105");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FAGRMNTID044 {
            get {
                return this.fAGRMNTID044Field;
            }
            set {
                this.fAGRMNTID044Field = value;
                this.RaisePropertyChanged("FAGRMNTID044");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VERSION_NO {
            get {
                return this.vERSION_NOField;
            }
            set {
                this.vERSION_NOField = value;
                this.RaisePropertyChanged("VERSION_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EXTERNAL_FA_ID {
            get {
                return this.eXTERNAL_FA_IDField;
            }
            set {
                this.eXTERNAL_FA_IDField = value;
                this.RaisePropertyChanged("EXTERNAL_FA_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DIM_WT_PROFILE {
            get {
                return this.dIM_WT_PROFILEField;
            }
            set {
                this.dIM_WT_PROFILEField = value;
                this.RaisePropertyChanged("DIM_WT_PROFILE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VALIDITY_START {
            get {
                return this.vALIDITY_STARTField;
            }
            set {
                this.vALIDITY_STARTField = value;
                this.RaisePropertyChanged("VALIDITY_START");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string VALIDITY_END {
            get {
                return this.vALIDITY_ENDField;
            }
            set {
                this.vALIDITY_ENDField = value;
                this.RaisePropertyChanged("VALIDITY_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FAGPRIOID104 {
            get {
                return this.fAGPRIOID104Field;
            }
            set {
                this.fAGPRIOID104Field = value;
                this.RaisePropertyChanged("FAGPRIOID104");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DOC_CURRENCY {
            get {
                return this.dOC_CURRENCYField;
            }
            set {
                this.dOC_CURRENCYField = value;
                this.RaisePropertyChanged("DOC_CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZXSY {
            get {
                return this.zXSYField;
            }
            set {
                this.zXSYField = value;
                this.RaisePropertyChanged("ZXSY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZBJLX {
            get {
                return this.zBJLXField;
            }
            set {
                this.zBJLXField = value;
                this.RaisePropertyChanged("ZBJLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ROOT_TEXT", Order=13)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAROOT_TEXT[] ROOT_TEXT {
            get {
                return this.rOOT_TEXTField;
            }
            set {
                this.rOOT_TEXTField = value;
                this.RaisePropertyChanged("ROOT_TEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAG_CONTRACTORS", Order=14)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_CONTRACTORS[] FAG_CONTRACTORS {
            get {
                return this.fAG_CONTRACTORSField;
            }
            set {
                this.fAG_CONTRACTORSField = value;
                this.RaisePropertyChanged("FAG_CONTRACTORS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAG_PARTY", Order=15)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_PARTY[] FAG_PARTY {
            get {
                return this.fAG_PARTYField;
            }
            set {
                this.fAG_PARTYField = value;
                this.RaisePropertyChanged("FAG_PARTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FAG_ITEM", Order=16)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEM[] FAG_ITEM {
            get {
                return this.fAG_ITEMField;
            }
            set {
                this.fAG_ITEMField = value;
                this.RaisePropertyChanged("FAG_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAROOT_TEXT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_CONTRACTORS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string oRG_UNITField;
        
        private string oRG_EXT_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ORG_UNIT {
            get {
                return this.oRG_UNITField;
            }
            set {
                this.oRG_UNITField = value;
                this.RaisePropertyChanged("ORG_UNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ORG_EXT_ID {
            get {
                return this.oRG_EXT_IDField;
            }
            set {
                this.oRG_EXT_IDField = value;
                this.RaisePropertyChanged("ORG_EXT_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_PARTY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string pTYINTID_ID133_IField;
        
        private string uUID001Field;
        
        private string pTY_RCO012_IField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PTYINTID_ID133_I {
            get {
                return this.pTYINTID_ID133_IField;
            }
            set {
                this.pTYINTID_ID133_IField = value;
                this.RaisePropertyChanged("PTYINTID_ID133_I");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UUID001 {
            get {
                return this.uUID001Field;
            }
            set {
                this.uUID001Field = value;
                this.RaisePropertyChanged("UUID001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PTY_RCO012_I {
            get {
                return this.pTY_RCO012_IField;
            }
            set {
                this.pTY_RCO012_IField = value;
                this.RaisePropertyChanged("PTY_RCO012_I");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string iTEM_NOField;
        
        private string iTEM_TYPEField;
        
        private string mTRField;
        
        private string sERVICE_PRODUCT_IDField;
        
        private string zTGFSField;
        
        private string sERVICE_TYPEField;
        
        private string pAR_KEYField;
        
        private string tCCS_UUIDField;
        
        private string tCCS_IDField;
        
        private string vALIDITY_STARTField;
        
        private string vALIDITY_ENDField;
        
        private string zBJFWField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMINS_DETAIL[] iNS_DETAILField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOT tCCS_ROOTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ITEM_NO {
            get {
                return this.iTEM_NOField;
            }
            set {
                this.iTEM_NOField = value;
                this.RaisePropertyChanged("ITEM_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ITEM_TYPE {
            get {
                return this.iTEM_TYPEField;
            }
            set {
                this.iTEM_TYPEField = value;
                this.RaisePropertyChanged("ITEM_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MTR {
            get {
                return this.mTRField;
            }
            set {
                this.mTRField = value;
                this.RaisePropertyChanged("MTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SERVICE_PRODUCT_ID {
            get {
                return this.sERVICE_PRODUCT_IDField;
            }
            set {
                this.sERVICE_PRODUCT_IDField = value;
                this.RaisePropertyChanged("SERVICE_PRODUCT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZTGFS {
            get {
                return this.zTGFSField;
            }
            set {
                this.zTGFSField = value;
                this.RaisePropertyChanged("ZTGFS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SERVICE_TYPE {
            get {
                return this.sERVICE_TYPEField;
            }
            set {
                this.sERVICE_TYPEField = value;
                this.RaisePropertyChanged("SERVICE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PAR_KEY {
            get {
                return this.pAR_KEYField;
            }
            set {
                this.pAR_KEYField = value;
                this.RaisePropertyChanged("PAR_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TCCS_UUID {
            get {
                return this.tCCS_UUIDField;
            }
            set {
                this.tCCS_UUIDField = value;
                this.RaisePropertyChanged("TCCS_UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TCCS_ID {
            get {
                return this.tCCS_IDField;
            }
            set {
                this.tCCS_IDField = value;
                this.RaisePropertyChanged("TCCS_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string VALIDITY_START {
            get {
                return this.vALIDITY_STARTField;
            }
            set {
                this.vALIDITY_STARTField = value;
                this.RaisePropertyChanged("VALIDITY_START");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string VALIDITY_END {
            get {
                return this.vALIDITY_ENDField;
            }
            set {
                this.vALIDITY_ENDField = value;
                this.RaisePropertyChanged("VALIDITY_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZBJFW {
            get {
                return this.zBJFWField;
            }
            set {
                this.zBJFWField = value;
                this.RaisePropertyChanged("ZBJFW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INS_DETAIL", Order=13)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMINS_DETAIL[] INS_DETAIL {
            get {
                return this.iNS_DETAILField;
            }
            set {
                this.iNS_DETAILField = value;
                this.RaisePropertyChanged("INS_DETAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOT TCCS_ROOT {
            get {
                return this.tCCS_ROOTField;
            }
            set {
                this.tCCS_ROOTField = value;
                this.RaisePropertyChanged("TCCS_ROOT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMINS_DETAIL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string iNS_IDField;
        
        private string sEQ_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string INS_ID {
            get {
                return this.iNS_IDField;
            }
            set {
                this.iNS_IDField = value;
                this.RaisePropertyChanged("INS_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SEQ_NUMBER {
            get {
                return this.sEQ_NUMBERField;
            }
            set {
                this.sEQ_NUMBERField = value;
                this.RaisePropertyChanged("SEQ_NUMBER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string tCCS_ID047Field;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEM[] tCCS_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TCCS_ID047 {
            get {
                return this.tCCS_ID047Field;
            }
            set {
                this.tCCS_ID047Field = value;
                this.RaisePropertyChanged("TCCS_ID047");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TCCS_ITEM", Order=2)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEM[] TCCS_ITEM {
            get {
                return this.tCCS_ITEMField;
            }
            set {
                this.tCCS_ITEMField = value;
                this.RaisePropertyChanged("TCCS_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string tCCALCRESINS040Field;
        
        private string tCET084Field;
        
        private string zSETTLE_ROLEField;
        
        private string zCZJS_ROLEField;
        
        private string zSETTLE_OBJField;
        
        private string oPERATIONCD102Field;
        
        private string rATE_TEMPLATE_IDField;
        
        private string rOUND_RULEField;
        
        private string cOST_PULL_STRATEGYField;
        
        private string sOURCE_CHARGEField;
        
        private string sTAGE_CATField;
        
        private string cLCRESBAS036Field;
        
        private string rULE113Field;
        
        private string cALC_METH_CODEField;
        
        private string tCC_ITEM_DESCRIPTIONField;
        
        private string cALC_METH_NAMEField;
        
        private string rULE101Field;
        
        private string aMOUNTField;
        
        private string cURRCODE016Field;
        
        private string rATE_IDField;
        
        private string cALC_REF_LINE_NOField;
        
        private string cALC_REF_TO_NOField;
        
        private string mIN_AMOUNTField;
        
        private string mAX_AMOUNTField;
        
        private string zKDDZXJEField;
        
        private string lINENR_AUTOField;
        
        private string rULE099Field;
        
        private string aNALYTICRELEVField;
        
        private string tCET084_COSTField;
        
        private string tARGET_ITEM_KEYField;
        
        private string zMZTSField;
        
        private string zYZDSFField;
        
        private string zSFBYField;
        
        private string zBYFYField;
        
        private string zDTCKField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_CALCRULE[] iTEM_CALCRULEField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_COST[] iTEM_COSTField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_DYFWLX[] iTEM_DYFWLXField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMTCCS_ZCZXG[] tCCS_ZCZXGField;
        
        private Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_TEXT[] iTEM_TEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TCCALCRESINS040 {
            get {
                return this.tCCALCRESINS040Field;
            }
            set {
                this.tCCALCRESINS040Field = value;
                this.RaisePropertyChanged("TCCALCRESINS040");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TCET084 {
            get {
                return this.tCET084Field;
            }
            set {
                this.tCET084Field = value;
                this.RaisePropertyChanged("TCET084");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZSETTLE_ROLE {
            get {
                return this.zSETTLE_ROLEField;
            }
            set {
                this.zSETTLE_ROLEField = value;
                this.RaisePropertyChanged("ZSETTLE_ROLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZCZJS_ROLE {
            get {
                return this.zCZJS_ROLEField;
            }
            set {
                this.zCZJS_ROLEField = value;
                this.RaisePropertyChanged("ZCZJS_ROLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZSETTLE_OBJ {
            get {
                return this.zSETTLE_OBJField;
            }
            set {
                this.zSETTLE_OBJField = value;
                this.RaisePropertyChanged("ZSETTLE_OBJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OPERATIONCD102 {
            get {
                return this.oPERATIONCD102Field;
            }
            set {
                this.oPERATIONCD102Field = value;
                this.RaisePropertyChanged("OPERATIONCD102");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RATE_TEMPLATE_ID {
            get {
                return this.rATE_TEMPLATE_IDField;
            }
            set {
                this.rATE_TEMPLATE_IDField = value;
                this.RaisePropertyChanged("RATE_TEMPLATE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ROUND_RULE {
            get {
                return this.rOUND_RULEField;
            }
            set {
                this.rOUND_RULEField = value;
                this.RaisePropertyChanged("ROUND_RULE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string COST_PULL_STRATEGY {
            get {
                return this.cOST_PULL_STRATEGYField;
            }
            set {
                this.cOST_PULL_STRATEGYField = value;
                this.RaisePropertyChanged("COST_PULL_STRATEGY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SOURCE_CHARGE {
            get {
                return this.sOURCE_CHARGEField;
            }
            set {
                this.sOURCE_CHARGEField = value;
                this.RaisePropertyChanged("SOURCE_CHARGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string STAGE_CAT {
            get {
                return this.sTAGE_CATField;
            }
            set {
                this.sTAGE_CATField = value;
                this.RaisePropertyChanged("STAGE_CAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CLCRESBAS036 {
            get {
                return this.cLCRESBAS036Field;
            }
            set {
                this.cLCRESBAS036Field = value;
                this.RaisePropertyChanged("CLCRESBAS036");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RULE113 {
            get {
                return this.rULE113Field;
            }
            set {
                this.rULE113Field = value;
                this.RaisePropertyChanged("RULE113");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CALC_METH_CODE {
            get {
                return this.cALC_METH_CODEField;
            }
            set {
                this.cALC_METH_CODEField = value;
                this.RaisePropertyChanged("CALC_METH_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TCC_ITEM_DESCRIPTION {
            get {
                return this.tCC_ITEM_DESCRIPTIONField;
            }
            set {
                this.tCC_ITEM_DESCRIPTIONField = value;
                this.RaisePropertyChanged("TCC_ITEM_DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CALC_METH_NAME {
            get {
                return this.cALC_METH_NAMEField;
            }
            set {
                this.cALC_METH_NAMEField = value;
                this.RaisePropertyChanged("CALC_METH_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string RULE101 {
            get {
                return this.rULE101Field;
            }
            set {
                this.rULE101Field = value;
                this.RaisePropertyChanged("RULE101");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
                this.RaisePropertyChanged("AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CURRCODE016 {
            get {
                return this.cURRCODE016Field;
            }
            set {
                this.cURRCODE016Field = value;
                this.RaisePropertyChanged("CURRCODE016");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string RATE_ID {
            get {
                return this.rATE_IDField;
            }
            set {
                this.rATE_IDField = value;
                this.RaisePropertyChanged("RATE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CALC_REF_LINE_NO {
            get {
                return this.cALC_REF_LINE_NOField;
            }
            set {
                this.cALC_REF_LINE_NOField = value;
                this.RaisePropertyChanged("CALC_REF_LINE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CALC_REF_TO_NO {
            get {
                return this.cALC_REF_TO_NOField;
            }
            set {
                this.cALC_REF_TO_NOField = value;
                this.RaisePropertyChanged("CALC_REF_TO_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string MIN_AMOUNT {
            get {
                return this.mIN_AMOUNTField;
            }
            set {
                this.mIN_AMOUNTField = value;
                this.RaisePropertyChanged("MIN_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string MAX_AMOUNT {
            get {
                return this.mAX_AMOUNTField;
            }
            set {
                this.mAX_AMOUNTField = value;
                this.RaisePropertyChanged("MAX_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ZKDDZXJE {
            get {
                return this.zKDDZXJEField;
            }
            set {
                this.zKDDZXJEField = value;
                this.RaisePropertyChanged("ZKDDZXJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string LINENR_AUTO {
            get {
                return this.lINENR_AUTOField;
            }
            set {
                this.lINENR_AUTOField = value;
                this.RaisePropertyChanged("LINENR_AUTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string RULE099 {
            get {
                return this.rULE099Field;
            }
            set {
                this.rULE099Field = value;
                this.RaisePropertyChanged("RULE099");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ANALYTICRELEV {
            get {
                return this.aNALYTICRELEVField;
            }
            set {
                this.aNALYTICRELEVField = value;
                this.RaisePropertyChanged("ANALYTICRELEV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string TCET084_COST {
            get {
                return this.tCET084_COSTField;
            }
            set {
                this.tCET084_COSTField = value;
                this.RaisePropertyChanged("TCET084_COST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string TARGET_ITEM_KEY {
            get {
                return this.tARGET_ITEM_KEYField;
            }
            set {
                this.tARGET_ITEM_KEYField = value;
                this.RaisePropertyChanged("TARGET_ITEM_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ZMZTS {
            get {
                return this.zMZTSField;
            }
            set {
                this.zMZTSField = value;
                this.RaisePropertyChanged("ZMZTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ZYZDSF {
            get {
                return this.zYZDSFField;
            }
            set {
                this.zYZDSFField = value;
                this.RaisePropertyChanged("ZYZDSF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ZSFBY {
            get {
                return this.zSFBYField;
            }
            set {
                this.zSFBYField = value;
                this.RaisePropertyChanged("ZSFBY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string ZBYFY {
            get {
                return this.zBYFYField;
            }
            set {
                this.zBYFYField = value;
                this.RaisePropertyChanged("ZBYFY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string ZDTCK {
            get {
                return this.zDTCKField;
            }
            set {
                this.zDTCKField = value;
                this.RaisePropertyChanged("ZDTCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM_CALCRULE", Order=36)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_CALCRULE[] ITEM_CALCRULE {
            get {
                return this.iTEM_CALCRULEField;
            }
            set {
                this.iTEM_CALCRULEField = value;
                this.RaisePropertyChanged("ITEM_CALCRULE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM_COST", Order=37)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_COST[] ITEM_COST {
            get {
                return this.iTEM_COSTField;
            }
            set {
                this.iTEM_COSTField = value;
                this.RaisePropertyChanged("ITEM_COST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM_DYFWLX", Order=38)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_DYFWLX[] ITEM_DYFWLX {
            get {
                return this.iTEM_DYFWLXField;
            }
            set {
                this.iTEM_DYFWLXField = value;
                this.RaisePropertyChanged("ITEM_DYFWLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TCCS_ZCZXG", Order=39)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMTCCS_ZCZXG[] TCCS_ZCZXG {
            get {
                return this.tCCS_ZCZXGField;
            }
            set {
                this.tCCS_ZCZXGField = value;
                this.RaisePropertyChanged("TCCS_ZCZXG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM_TEXT", Order=40)]
        public Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_TEXT[] ITEM_TEXT {
            get {
                return this.iTEM_TEXTField;
            }
            set {
                this.iTEM_TEXTField = value;
                this.RaisePropertyChanged("ITEM_TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_CALCRULE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string cALC_BASE_CODEField;
        
        private string qTY_VALUEField;
        
        private string qTY_UNIT_CField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CALC_BASE_CODE {
            get {
                return this.cALC_BASE_CODEField;
            }
            set {
                this.cALC_BASE_CODEField = value;
                this.RaisePropertyChanged("CALC_BASE_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string QTY_VALUE {
            get {
                return this.qTY_VALUEField;
            }
            set {
                this.qTY_VALUEField = value;
                this.RaisePropertyChanged("QTY_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string QTY_UNIT_C {
            get {
                return this.qTY_UNIT_CField;
            }
            set {
                this.qTY_UNIT_CField = value;
                this.RaisePropertyChanged("QTY_UNIT_C");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_COST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string tCET084Field;
        
        private string tCCLASS037Field;
        
        private string cHRGCATCD021_IField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TCET084 {
            get {
                return this.tCET084Field;
            }
            set {
                this.tCET084Field = value;
                this.RaisePropertyChanged("TCET084");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TCCLASS037 {
            get {
                return this.tCCLASS037Field;
            }
            set {
                this.tCCLASS037Field = value;
                this.RaisePropertyChanged("TCCLASS037");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CHRGCATCD021_I {
            get {
                return this.cHRGCATCD021_IField;
            }
            set {
                this.cHRGCATCD021_IField = value;
                this.RaisePropertyChanged("CHRGCATCD021_I");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_DYFWLX : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string zLINE_NOField;
        
        private string zTRANSSRVREQ_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZLINE_NO {
            get {
                return this.zLINE_NOField;
            }
            set {
                this.zLINE_NOField = value;
                this.RaisePropertyChanged("ZLINE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZTRANSSRVREQ_CODE {
            get {
                return this.zTRANSSRVREQ_CODEField;
            }
            set {
                this.zTRANSSRVREQ_CODEField = value;
                this.RaisePropertyChanged("ZTRANSSRVREQ_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMTCCS_ZCZXG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string zCONDITION_NAMEField;
        
        private string zOPERATORField;
        
        private string zDVALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ZCONDITION_NAME {
            get {
                return this.zCONDITION_NAMEField;
            }
            set {
                this.zCONDITION_NAMEField = value;
                this.RaisePropertyChanged("ZCONDITION_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZOPERATOR {
            get {
                return this.zOPERATORField;
            }
            set {
                this.zOPERATORField = value;
                this.RaisePropertyChanged("ZOPERATOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZDVALUE {
            get {
                return this.zDVALUEField;
            }
            set {
                this.zDVALUEField = value;
                this.RaisePropertyChanged("ZDVALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
    public partial class Z2FM_SQ_FWA_SEARCH_RESET_FWAFAG_ITEMTCCS_ROOTTCCS_ITEMITEM_TEXT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kEYField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KEY {
            get {
                return this.kEYField;
            }
            set {
                this.kEYField = value;
                this.RaisePropertyChanged("KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.INPUT.Z2FM_SQ_FWA_SEARCH", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.INPUT.Z2FM_SQ_FWA_SEARCH")]
        public Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH Z2FM_SQ_FWA_SEARCH;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH Z2FM_SQ_FWA_SEARCH) {
            this.Z2FM_SQ_FWA_SEARCH = Z2FM_SQ_FWA_SEARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://BizTalk.RFC.TM_CRM_703.Schemas.OUTPUT.Z2FM_SQ_FWA_SEARCH_RES")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ET_FWA", IsNullable=false)]
        public Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH_RESET_FWA[] Z2FM_SQ_FWA_SEARCH_RES;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH_RESET_FWA[] Z2FM_SQ_FWA_SEARCH_RES) {
            this.Z2FM_SQ_FWA_SEARCH_RES = Z2FM_SQ_FWA_SEARCH_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapChannel : Oncontrol3.Web.FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap>, Oncontrol3.Web.FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.FWA703.Operation_1Response Oncontrol3.Web.FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap.Operation_1(Oncontrol3.Web.FWA703.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH_RESET_FWA[] Operation_1(Oncontrol3.Web.FWA703.Z2FM_SQ_FWA_SEARCH Z2FM_SQ_FWA_SEARCH) {
            Oncontrol3.Web.FWA703.Operation_1Request inValue = new Oncontrol3.Web.FWA703.Operation_1Request();
            inValue.Z2FM_SQ_FWA_SEARCH = Z2FM_SQ_FWA_SEARCH;
            Oncontrol3.Web.FWA703.Operation_1Response retVal = ((Oncontrol3.Web.FWA703.BizTalk_RFC_TM_CRM_703_Orchestration_InboundSoap)(this)).Operation_1(inValue);
            return retVal.Z2FM_SQ_FWA_SEARCH_RES;
        }
    }
}
