//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.MDMBSV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap {
        
        // CODEGEN: 消息部分命名空间 http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES 以后生成的消息协定与默认值(http://tempuri.org/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_025_MDMClient_Inbound/Exec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_SQ_RFC_CALC_BASE_RES")]
        Oncontrol3.Web.MDMBSV.ExecResponse Exec(Oncontrol3.Web.MDMBSV.ExecRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.INPUT.Z2FM_SQ_RFC_CALC_BASE")]
    public partial class Z2FM_SQ_RFC_CALC_BASE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_SELECT_ALLField;
        
        private Z2FM_SQ_RFC_CALC_BASEIT_CALC_BASE[] iT_CALC_BASEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IV_SELECT_ALL {
            get {
                return this.iV_SELECT_ALLField;
            }
            set {
                this.iV_SELECT_ALLField = value;
                this.RaisePropertyChanged("IV_SELECT_ALL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IT_CALC_BASE", Order=1)]
        public Z2FM_SQ_RFC_CALC_BASEIT_CALC_BASE[] IT_CALC_BASE {
            get {
                return this.iT_CALC_BASEField;
            }
            set {
                this.iT_CALC_BASEField = value;
                this.RaisePropertyChanged("IT_CALC_BASE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.INPUT.Z2FM_SQ_RFC_CALC_BASE")]
    public partial class Z2FM_SQ_RFC_CALC_BASEIT_CALC_BASE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cALC_BASEField;
        
        private string sAVE_TYPEField;
        
        private string lOCATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CALC_BASE {
            get {
                return this.cALC_BASEField;
            }
            set {
                this.cALC_BASEField = value;
                this.RaisePropertyChanged("CALC_BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SAVE_TYPE {
            get {
                return this.sAVE_TYPEField;
            }
            set {
                this.sAVE_TYPEField = value;
                this.RaisePropertyChanged("SAVE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
                this.RaisePropertyChanged("LOCATION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_SQ_RFC_CALC_BASE_RESES_RETURN eS_RETURNField;
        
        private Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFO[] eT_CALC_BASE_INFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_SQ_RFC_CALC_BASE_RESES_RETURN ES_RETURN {
            get {
                return this.eS_RETURNField;
            }
            set {
                this.eS_RETURNField = value;
                this.RaisePropertyChanged("ES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_CALC_BASE_INFO", Order=1)]
        public Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFO[] ET_CALC_BASE_INFO {
            get {
                return this.eT_CALC_BASE_INFOField;
            }
            set {
                this.eT_CALC_BASE_INFOField = value;
                this.RaisePropertyChanged("ET_CALC_BASE_INFO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mSG_TYPEField;
        
        private string mSG_IDField;
        
        private string mSG_NOField;
        
        private string mSG_TEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MSG_TYPE {
            get {
                return this.mSG_TYPEField;
            }
            set {
                this.mSG_TYPEField = value;
                this.RaisePropertyChanged("MSG_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MSG_ID {
            get {
                return this.mSG_IDField;
            }
            set {
                this.mSG_IDField = value;
                this.RaisePropertyChanged("MSG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MSG_NO {
            get {
                return this.mSG_NOField;
            }
            set {
                this.mSG_NOField = value;
                this.RaisePropertyChanged("MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MSG_TEXT {
            get {
                return this.mSG_TEXTField;
            }
            set {
                this.mSG_TEXTField = value;
                this.RaisePropertyChanged("MSG_TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cALC_BASEField;
        
        private string dESCRIPTIONField;
        
        private string sAVE_TYPEField;
        
        private Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOT_VAL_DOMAIN[] t_VAL_DOMAINField;
        
        private Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLE s_VAL_TABLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CALC_BASE {
            get {
                return this.cALC_BASEField;
            }
            set {
                this.cALC_BASEField = value;
                this.RaisePropertyChanged("CALC_BASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SAVE_TYPE {
            get {
                return this.sAVE_TYPEField;
            }
            set {
                this.sAVE_TYPEField = value;
                this.RaisePropertyChanged("SAVE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_VAL_DOMAIN", Order=3)]
        public Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOT_VAL_DOMAIN[] T_VAL_DOMAIN {
            get {
                return this.t_VAL_DOMAINField;
            }
            set {
                this.t_VAL_DOMAINField = value;
                this.RaisePropertyChanged("T_VAL_DOMAIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLE S_VAL_TABLE {
            get {
                return this.s_VAL_TABLEField;
            }
            set {
                this.s_VAL_TABLEField = value;
                this.RaisePropertyChanged("S_VAL_TABLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOT_VAL_DOMAIN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vALField;
        
        private string dESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VAL {
            get {
                return this.vALField;
            }
            set {
                this.vALField = value;
                this.RaisePropertyChanged("VAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DES {
            get {
                return this.dESField;
            }
            set {
                this.dESField = value;
                this.RaisePropertyChanged("DES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_STRC[] tABLE_STRCField;
        
        private Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_VALUE[] tABLE_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TABLE_STRC", Order=0)]
        public Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_STRC[] TABLE_STRC {
            get {
                return this.tABLE_STRCField;
            }
            set {
                this.tABLE_STRCField = value;
                this.RaisePropertyChanged("TABLE_STRC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TABLE_VALUE", Order=1)]
        public Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_VALUE[] TABLE_VALUE {
            get {
                return this.tABLE_VALUEField;
            }
            set {
                this.tABLE_VALUEField = value;
                this.RaisePropertyChanged("TABLE_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_STRC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tABNAMEField;
        
        private string fIELDNAMEField;
        
        private string kEYFLAGField;
        
        private string pOSITIONField;
        
        private string iNTTYPEField;
        
        private string iNTLENField;
        
        private string dDLANGUAGEField;
        
        private string dDTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TABNAME {
            get {
                return this.tABNAMEField;
            }
            set {
                this.tABNAMEField = value;
                this.RaisePropertyChanged("TABNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FIELDNAME {
            get {
                return this.fIELDNAMEField;
            }
            set {
                this.fIELDNAMEField = value;
                this.RaisePropertyChanged("FIELDNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KEYFLAG {
            get {
                return this.kEYFLAGField;
            }
            set {
                this.kEYFLAGField = value;
                this.RaisePropertyChanged("KEYFLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string POSITION {
            get {
                return this.pOSITIONField;
            }
            set {
                this.pOSITIONField = value;
                this.RaisePropertyChanged("POSITION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string INTTYPE {
            get {
                return this.iNTTYPEField;
            }
            set {
                this.iNTTYPEField = value;
                this.RaisePropertyChanged("INTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string INTLEN {
            get {
                return this.iNTLENField;
            }
            set {
                this.iNTLENField = value;
                this.RaisePropertyChanged("INTLEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DDLANGUAGE {
            get {
                return this.dDLANGUAGEField;
            }
            set {
                this.dDLANGUAGEField = value;
                this.RaisePropertyChanged("DDLANGUAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DDTEXT {
            get {
                return this.dDTEXTField;
            }
            set {
                this.dDTEXTField = value;
                this.RaisePropertyChanged("DDTEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
    public partial class Z2FM_SQ_RFC_CALC_BASE_RESET_CALC_BASE_INFOS_VAL_TABLETABLE_VALUE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOLUMN1Field;
        
        private string cOLUMN2Field;
        
        private string cOLUMN3Field;
        
        private string cOLUMN4Field;
        
        private string cOLUMN5Field;
        
        private string cOLUMN6Field;
        
        private string cOLUMN7Field;
        
        private string cOLUMN8Field;
        
        private string cOLUMN9Field;
        
        private string cOLUMN10Field;
        
        private string cOLUMN11Field;
        
        private string cOLUMN12Field;
        
        private string cOLUMN13Field;
        
        private string cOLUMN14Field;
        
        private string cOLUMN15Field;
        
        private string cOLUMN16Field;
        
        private string cOLUMN17Field;
        
        private string cOLUMN18Field;
        
        private string cOLUMN19Field;
        
        private string cOLUMN20Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string COLUMN1 {
            get {
                return this.cOLUMN1Field;
            }
            set {
                this.cOLUMN1Field = value;
                this.RaisePropertyChanged("COLUMN1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COLUMN2 {
            get {
                return this.cOLUMN2Field;
            }
            set {
                this.cOLUMN2Field = value;
                this.RaisePropertyChanged("COLUMN2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COLUMN3 {
            get {
                return this.cOLUMN3Field;
            }
            set {
                this.cOLUMN3Field = value;
                this.RaisePropertyChanged("COLUMN3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string COLUMN4 {
            get {
                return this.cOLUMN4Field;
            }
            set {
                this.cOLUMN4Field = value;
                this.RaisePropertyChanged("COLUMN4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string COLUMN5 {
            get {
                return this.cOLUMN5Field;
            }
            set {
                this.cOLUMN5Field = value;
                this.RaisePropertyChanged("COLUMN5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string COLUMN6 {
            get {
                return this.cOLUMN6Field;
            }
            set {
                this.cOLUMN6Field = value;
                this.RaisePropertyChanged("COLUMN6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string COLUMN7 {
            get {
                return this.cOLUMN7Field;
            }
            set {
                this.cOLUMN7Field = value;
                this.RaisePropertyChanged("COLUMN7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string COLUMN8 {
            get {
                return this.cOLUMN8Field;
            }
            set {
                this.cOLUMN8Field = value;
                this.RaisePropertyChanged("COLUMN8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string COLUMN9 {
            get {
                return this.cOLUMN9Field;
            }
            set {
                this.cOLUMN9Field = value;
                this.RaisePropertyChanged("COLUMN9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string COLUMN10 {
            get {
                return this.cOLUMN10Field;
            }
            set {
                this.cOLUMN10Field = value;
                this.RaisePropertyChanged("COLUMN10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string COLUMN11 {
            get {
                return this.cOLUMN11Field;
            }
            set {
                this.cOLUMN11Field = value;
                this.RaisePropertyChanged("COLUMN11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string COLUMN12 {
            get {
                return this.cOLUMN12Field;
            }
            set {
                this.cOLUMN12Field = value;
                this.RaisePropertyChanged("COLUMN12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string COLUMN13 {
            get {
                return this.cOLUMN13Field;
            }
            set {
                this.cOLUMN13Field = value;
                this.RaisePropertyChanged("COLUMN13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string COLUMN14 {
            get {
                return this.cOLUMN14Field;
            }
            set {
                this.cOLUMN14Field = value;
                this.RaisePropertyChanged("COLUMN14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string COLUMN15 {
            get {
                return this.cOLUMN15Field;
            }
            set {
                this.cOLUMN15Field = value;
                this.RaisePropertyChanged("COLUMN15");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string COLUMN16 {
            get {
                return this.cOLUMN16Field;
            }
            set {
                this.cOLUMN16Field = value;
                this.RaisePropertyChanged("COLUMN16");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string COLUMN17 {
            get {
                return this.cOLUMN17Field;
            }
            set {
                this.cOLUMN17Field = value;
                this.RaisePropertyChanged("COLUMN17");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string COLUMN18 {
            get {
                return this.cOLUMN18Field;
            }
            set {
                this.cOLUMN18Field = value;
                this.RaisePropertyChanged("COLUMN18");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string COLUMN19 {
            get {
                return this.cOLUMN19Field;
            }
            set {
                this.cOLUMN19Field = value;
                this.RaisePropertyChanged("COLUMN19");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string COLUMN20 {
            get {
                return this.cOLUMN20Field;
            }
            set {
                this.cOLUMN20Field = value;
                this.RaisePropertyChanged("COLUMN20");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Exec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.INPUT.Z2FM_SQ_RFC_CALC_BASE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.INPUT.Z2FM_SQ_RFC_CALC_BASE")]
        public Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE Z2FM_SQ_RFC_CALC_BASE;
        
        public ExecRequest() {
        }
        
        public ExecRequest(Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE Z2FM_SQ_RFC_CALC_BASE) {
            this.Z2FM_SQ_RFC_CALC_BASE = Z2FM_SQ_RFC_CALC_BASE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_025.Schemas.OUTPUT.Z2FM_SQ_RFC_CALC_BASE_RES")]
        public Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE_RES Z2FM_SQ_RFC_CALC_BASE_RES;
        
        public ExecResponse() {
        }
        
        public ExecResponse(Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE_RES Z2FM_SQ_RFC_CALC_BASE_RES) {
            this.Z2FM_SQ_RFC_CALC_BASE_RES = Z2FM_SQ_RFC_CALC_BASE_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapChannel : Oncontrol3.Web.MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap>, Oncontrol3.Web.MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.MDMBSV.ExecResponse Oncontrol3.Web.MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap.Exec(Oncontrol3.Web.MDMBSV.ExecRequest request) {
            return base.Channel.Exec(request);
        }
        
        public Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE_RES Exec(Oncontrol3.Web.MDMBSV.Z2FM_SQ_RFC_CALC_BASE Z2FM_SQ_RFC_CALC_BASE) {
            Oncontrol3.Web.MDMBSV.ExecRequest inValue = new Oncontrol3.Web.MDMBSV.ExecRequest();
            inValue.Z2FM_SQ_RFC_CALC_BASE = Z2FM_SQ_RFC_CALC_BASE;
            Oncontrol3.Web.MDMBSV.ExecResponse retVal = ((Oncontrol3.Web.MDMBSV.BizTalk_RFC_TM_CRM_025_MDMClient_InboundSoap)(this)).Exec(inValue);
            return retVal.Z2FM_SQ_RFC_CALC_BASE_RES;
        }
    }
}
