//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.COND803 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Z2FM_COND_DELETE", Namespace="http://BizTalk.RFC.TM_CRM_803.Schemas.INPUT.Z2FM_COND_DELETE")]
    [System.SerializableAttribute()]
    public partial class Z2FM_COND_DELETE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IV_COND_KEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IV_SIMULATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] IV_COND_KEY {
            get {
                return this.IV_COND_KEYField;
            }
            set {
                if ((object.ReferenceEquals(this.IV_COND_KEYField, value) != true)) {
                    this.IV_COND_KEYField = value;
                    this.RaisePropertyChanged("IV_COND_KEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IV_SIMULATE {
            get {
                return this.IV_SIMULATEField;
            }
            set {
                if ((object.ReferenceEquals(this.IV_SIMULATEField, value) != true)) {
                    this.IV_SIMULATEField = value;
                    this.RaisePropertyChanged("IV_SIMULATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Z2FM_COND_DELETE_RES", Namespace="http://BizTalk.RFC.TM_CRM_803.Schemas.OUTPUT.Z2FM_COND_DELETE_RES", ItemName="ET_MESSAGE")]
    [System.SerializableAttribute()]
    public class Z2FM_COND_DELETE_RES : System.Collections.Generic.List<Oncontrol3.Web.COND803.ET_MESSAGE> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ET_MESSAGE", Namespace="http://BizTalk.RFC.TM_CRM_803.Schemas.OUTPUT.Z2FM_COND_DELETE_RES")]
    [System.SerializableAttribute()]
    public partial class ET_MESSAGE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOG_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOG_MSG_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESSAGE_V4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAMETERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIELDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYSTEMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.TYPEField, value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NUMBER {
            get {
                return this.NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMBERField, value) != true)) {
                    this.NUMBERField = value;
                    this.RaisePropertyChanged("NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LOG_NO {
            get {
                return this.LOG_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOG_NOField, value) != true)) {
                    this.LOG_NOField = value;
                    this.RaisePropertyChanged("LOG_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.LOG_MSG_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOG_MSG_NOField, value) != true)) {
                    this.LOG_MSG_NOField = value;
                    this.RaisePropertyChanged("LOG_MSG_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.MESSAGE_V1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V1Field, value) != true)) {
                    this.MESSAGE_V1Field = value;
                    this.RaisePropertyChanged("MESSAGE_V1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.MESSAGE_V2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V2Field, value) != true)) {
                    this.MESSAGE_V2Field = value;
                    this.RaisePropertyChanged("MESSAGE_V2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.MESSAGE_V3Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V3Field, value) != true)) {
                    this.MESSAGE_V3Field = value;
                    this.RaisePropertyChanged("MESSAGE_V3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.MESSAGE_V4Field;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGE_V4Field, value) != true)) {
                    this.MESSAGE_V4Field = value;
                    this.RaisePropertyChanged("MESSAGE_V4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PARAMETER {
            get {
                return this.PARAMETERField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAMETERField, value) != true)) {
                    this.PARAMETERField = value;
                    this.RaisePropertyChanged("PARAMETER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ROW {
            get {
                return this.ROWField;
            }
            set {
                if ((object.ReferenceEquals(this.ROWField, value) != true)) {
                    this.ROWField = value;
                    this.RaisePropertyChanged("ROW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FIELD {
            get {
                return this.FIELDField;
            }
            set {
                if ((object.ReferenceEquals(this.FIELDField, value) != true)) {
                    this.FIELDField = value;
                    this.RaisePropertyChanged("FIELD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SYSTEM {
            get {
                return this.SYSTEMField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSTEMField, value) != true)) {
                    this.SYSTEMField = value;
                    this.RaisePropertyChanged("SYSTEM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap {
        
        // CODEGEN: 命名空间 http://BizTalk.RFC.TM_CRM_803.Schemas.INPUT.Z2FM_COND_DELETE 的元素名称 Z2FM_COND_DELETE 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_803_Orchestration_Inbound/Operation_1", ReplyAction="*")]
        Oncontrol3.Web.COND803.Operation_1Response Operation_1(Oncontrol3.Web.COND803.Operation_1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Operation_1", Namespace="http://tempuri.org/", Order=0)]
        public Oncontrol3.Web.COND803.Operation_1RequestBody Body;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(Oncontrol3.Web.COND803.Operation_1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BizTalk.RFC.TM_CRM_803.Schemas.INPUT.Z2FM_COND_DELETE")]
    public partial class Operation_1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Oncontrol3.Web.COND803.Z2FM_COND_DELETE Z2FM_COND_DELETE;
        
        public Operation_1RequestBody() {
        }
        
        public Operation_1RequestBody(Oncontrol3.Web.COND803.Z2FM_COND_DELETE Z2FM_COND_DELETE) {
            this.Z2FM_COND_DELETE = Z2FM_COND_DELETE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Operation_1Response", Namespace="http://tempuri.org/", Order=0)]
        public Oncontrol3.Web.COND803.Operation_1ResponseBody Body;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(Oncontrol3.Web.COND803.Operation_1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://BizTalk.RFC.TM_CRM_803.Schemas.OUTPUT.Z2FM_COND_DELETE_RES")]
    public partial class Operation_1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Oncontrol3.Web.COND803.Z2FM_COND_DELETE_RES Z2FM_COND_DELETE_RES;
        
        public Operation_1ResponseBody() {
        }
        
        public Operation_1ResponseBody(Oncontrol3.Web.COND803.Z2FM_COND_DELETE_RES Z2FM_COND_DELETE_RES) {
            this.Z2FM_COND_DELETE_RES = Z2FM_COND_DELETE_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapChannel : Oncontrol3.Web.COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap>, Oncontrol3.Web.COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.COND803.Operation_1Response Oncontrol3.Web.COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap.Operation_1(Oncontrol3.Web.COND803.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public Oncontrol3.Web.COND803.Z2FM_COND_DELETE_RES Operation_1(Oncontrol3.Web.COND803.Z2FM_COND_DELETE Z2FM_COND_DELETE) {
            Oncontrol3.Web.COND803.Operation_1Request inValue = new Oncontrol3.Web.COND803.Operation_1Request();
            inValue.Body = new Oncontrol3.Web.COND803.Operation_1RequestBody();
            inValue.Body.Z2FM_COND_DELETE = Z2FM_COND_DELETE;
            Oncontrol3.Web.COND803.Operation_1Response retVal = ((Oncontrol3.Web.COND803.BizTalk_RFC_TM_CRM_803_Orchestration_InboundSoap)(this)).Operation_1(inValue);
            return retVal.Body.Z2FM_COND_DELETE_RES;
        }
    }
}
