//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.70.14/SSOWebService/SsoService.asmx")]
        public string Oncontrol3_Web_BSC_SSO_LOGIN_SsoService {
            get {
                return ((string)(this["Oncontrol3_Web_BSC_SSO_LOGIN_SsoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.60.189:9090/services/createGetCrm")]
        public string Oncontrol3_Web_GetDataFromXSYByCustomerNo_CreateGetCRM {
            get {
                return ((string)(this["Oncontrol3_Web_GetDataFromXSYByCustomerNo_CreateGetCRM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.60.189:9090/services/createQuotation")]
        public string Oncontrol3_Web_BJWriteback_CreateQuotation {
            get {
                return ((string)(this["Oncontrol3_Web_BJWriteback_CreateQuotation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.70.63:9090/services/updateQuotation")]
        public string Oncontrol3_Web_BJWriteBackUpdate_UpdateQuotation {
            get {
                return ((string)(this["Oncontrol3_Web_BJWriteBackUpdate_UpdateQuotation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:20026/logservice.asmx")]
        public string Oncontrol3_Web_localhost_LogService {
            get {
                return ((string)(this["Oncontrol3_Web_localhost_LogService"]));
            }
        }
    }
}
