//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BJWebServiceSoap")]
    public interface BJWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BJ(string type, string userid, string customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnZuZhi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReturnZuZhi(string xxx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MDMPRODUCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActiveRecordHooksBase))]
        bool MDMPRODUCT(Oncontrol3.Web.ServiceReference1.CRM_PRODUCT prd);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_PRODUCT : CRMModelBaseOfCRM_PRODUCT {
        
        private System.Nullable<decimal> mLVField;
        
        private string idField;
        
        private string pRODUCTSNAMEField;
        
        private string pRODUCTDESCRIPTIONField;
        
        private string sTATUSField;
        
        private string cREATEIDField;
        
        private string cREATENAMEField;
        
        private System.Nullable<System.DateTime> cREATETIMEField;
        
        private string pRODUCTSCODEField;
        
        private System.Nullable<System.DateTime> uPDATETIMEField;
        
        private string uPDATENAMEField;
        
        private string uPDATEIDField;
        
        private string pRODUCTUSERField;
        
        private string pRODUCTUSERIDField;
        
        private string fATHERIDField;
        
        private string fATHERNAMEField;
        
        private string dEPTIDField;
        
        private string dEPTNAMEField;
        
        private string dIVISIONField;
        
        private string rEMARKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> MLV {
            get {
                return this.mLVField;
            }
            set {
                this.mLVField = value;
                this.RaisePropertyChanged("MLV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PRODUCTSNAME {
            get {
                return this.pRODUCTSNAMEField;
            }
            set {
                this.pRODUCTSNAMEField = value;
                this.RaisePropertyChanged("PRODUCTSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PRODUCTDESCRIPTION {
            get {
                return this.pRODUCTDESCRIPTIONField;
            }
            set {
                this.pRODUCTDESCRIPTIONField = value;
                this.RaisePropertyChanged("PRODUCTDESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CREATEID {
            get {
                return this.cREATEIDField;
            }
            set {
                this.cREATEIDField = value;
                this.RaisePropertyChanged("CREATEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CREATENAME {
            get {
                return this.cREATENAMEField;
            }
            set {
                this.cREATENAMEField = value;
                this.RaisePropertyChanged("CREATENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> CREATETIME {
            get {
                return this.cREATETIMEField;
            }
            set {
                this.cREATETIMEField = value;
                this.RaisePropertyChanged("CREATETIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PRODUCTSCODE {
            get {
                return this.pRODUCTSCODEField;
            }
            set {
                this.pRODUCTSCODEField = value;
                this.RaisePropertyChanged("PRODUCTSCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> UPDATETIME {
            get {
                return this.uPDATETIMEField;
            }
            set {
                this.uPDATETIMEField = value;
                this.RaisePropertyChanged("UPDATETIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UPDATENAME {
            get {
                return this.uPDATENAMEField;
            }
            set {
                this.uPDATENAMEField = value;
                this.RaisePropertyChanged("UPDATENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UPDATEID {
            get {
                return this.uPDATEIDField;
            }
            set {
                this.uPDATEIDField = value;
                this.RaisePropertyChanged("UPDATEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PRODUCTUSER {
            get {
                return this.pRODUCTUSERField;
            }
            set {
                this.pRODUCTUSERField = value;
                this.RaisePropertyChanged("PRODUCTUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PRODUCTUSERID {
            get {
                return this.pRODUCTUSERIDField;
            }
            set {
                this.pRODUCTUSERIDField = value;
                this.RaisePropertyChanged("PRODUCTUSERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FATHERID {
            get {
                return this.fATHERIDField;
            }
            set {
                this.fATHERIDField = value;
                this.RaisePropertyChanged("FATHERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FATHERNAME {
            get {
                return this.fATHERNAMEField;
            }
            set {
                this.fATHERNAMEField = value;
                this.RaisePropertyChanged("FATHERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
                this.RaisePropertyChanged("DEPTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DEPTNAME {
            get {
                return this.dEPTNAMEField;
            }
            set {
                this.dEPTNAMEField = value;
                this.RaisePropertyChanged("DEPTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
                this.RaisePropertyChanged("DIVISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class CRMModelBaseOfCRM_PRODUCT : ModelBaseOfCRM_PRODUCT {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRMModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ModelBaseOfCRM_PRODUCT : EntityBaseOfCRM_PRODUCT {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRMModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityBaseOfCRM_PRODUCT : ActiveRecordBaseOfCRM_PRODUCT {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRMModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ActiveRecordBaseOfCRM_PRODUCT : ActiveRecordBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActiveRecordBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRMModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ActiveRecordBase : ActiveRecordHooksBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActiveRecordBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActiveRecordBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRMModelBaseOfCRM_PRODUCT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRM_PRODUCT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ActiveRecordHooksBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BJWebServiceSoapChannel : Oncontrol3.Web.ServiceReference1.BJWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BJWebServiceSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.ServiceReference1.BJWebServiceSoap>, Oncontrol3.Web.ServiceReference1.BJWebServiceSoap {
        
        public BJWebServiceSoapClient() {
        }
        
        public BJWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BJWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BJWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BJWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BJ(string type, string userid, string customerid) {
            return base.Channel.BJ(type, userid, customerid);
        }
        
        public string ReturnZuZhi(string xxx) {
            return base.Channel.ReturnZuZhi(xxx);
        }
        
        public bool MDMPRODUCT(Oncontrol3.Web.ServiceReference1.CRM_PRODUCT prd) {
            return base.Channel.MDMPRODUCT(prd);
        }
    }
}
