//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aim.Portal.ServicesProvider.LogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogService.LogServiceSoap")]
    public interface LogServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entityName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogEntity", ReplyAction="*")]
        Aim.Portal.ServicesProvider.LogService.LogEntityResponse LogEntity(Aim.Portal.ServicesProvider.LogService.LogEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LogEntity", ReplyAction="*")]
        System.IAsyncResult BeginLogEntity(Aim.Portal.ServicesProvider.LogService.LogEntityRequest request, System.AsyncCallback callback, object asyncState);
        
        Aim.Portal.ServicesProvider.LogService.LogEntityResponse EndLogEntity(System.IAsyncResult result);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 entityName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogProperty", ReplyAction="*")]
        Aim.Portal.ServicesProvider.LogService.LogPropertyResponse LogProperty(Aim.Portal.ServicesProvider.LogService.LogPropertyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LogProperty", ReplyAction="*")]
        System.IAsyncResult BeginLogProperty(Aim.Portal.ServicesProvider.LogService.LogPropertyRequest request, System.AsyncCallback callback, object asyncState);
        
        Aim.Portal.ServicesProvider.LogService.LogPropertyResponse EndLogProperty(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogEntityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogEntity", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.LogService.LogEntityRequestBody Body;
        
        public LogEntityRequest() {
        }
        
        public LogEntityRequest(Aim.Portal.ServicesProvider.LogService.LogEntityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogEntityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string entityName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime createTime;
        
        public LogEntityRequestBody() {
        }
        
        public LogEntityRequestBody(string entityName, string action, string message, string userId, string userName, System.DateTime createTime) {
            this.entityName = entityName;
            this.action = action;
            this.message = message;
            this.userId = userId;
            this.userName = userName;
            this.createTime = createTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogEntityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.LogService.LogEntityResponseBody Body;
        
        public LogEntityResponse() {
        }
        
        public LogEntityResponse(Aim.Portal.ServicesProvider.LogService.LogEntityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogEntityResponseBody {
        
        public LogEntityResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogPropertyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogProperty", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.LogService.LogPropertyRequestBody Body;
        
        public LogPropertyRequest() {
        }
        
        public LogPropertyRequest(Aim.Portal.ServicesProvider.LogService.LogPropertyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogPropertyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string entityName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string propertyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oldValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime createTime;
        
        public LogPropertyRequestBody() {
        }
        
        public LogPropertyRequestBody(string entityName, string propertyName, string oldValue, string newValue, string userId, string userName, System.DateTime createTime) {
            this.entityName = entityName;
            this.propertyName = propertyName;
            this.oldValue = oldValue;
            this.newValue = newValue;
            this.userId = userId;
            this.userName = userName;
            this.createTime = createTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogPropertyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogPropertyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.LogService.LogPropertyResponseBody Body;
        
        public LogPropertyResponse() {
        }
        
        public LogPropertyResponse(Aim.Portal.ServicesProvider.LogService.LogPropertyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogPropertyResponseBody {
        
        public LogPropertyResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogServiceSoapChannel : Aim.Portal.ServicesProvider.LogService.LogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServiceSoapClient : System.ServiceModel.ClientBase<Aim.Portal.ServicesProvider.LogService.LogServiceSoap>, Aim.Portal.ServicesProvider.LogService.LogServiceSoap {
        
        private BeginOperationDelegate onBeginLogEntityDelegate;
        
        private EndOperationDelegate onEndLogEntityDelegate;
        
        private System.Threading.SendOrPostCallback onLogEntityCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogPropertyDelegate;
        
        private EndOperationDelegate onEndLogPropertyDelegate;
        
        private System.Threading.SendOrPostCallback onLogPropertyCompletedDelegate;
        
        public LogServiceSoapClient() {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LogEntityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LogPropertyCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.LogService.LogEntityResponse Aim.Portal.ServicesProvider.LogService.LogServiceSoap.LogEntity(Aim.Portal.ServicesProvider.LogService.LogEntityRequest request) {
            return base.Channel.LogEntity(request);
        }
        
        public void LogEntity(string entityName, string action, string message, string userId, string userName, System.DateTime createTime) {
            Aim.Portal.ServicesProvider.LogService.LogEntityRequest inValue = new Aim.Portal.ServicesProvider.LogService.LogEntityRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.LogService.LogEntityRequestBody();
            inValue.Body.entityName = entityName;
            inValue.Body.action = action;
            inValue.Body.message = message;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.createTime = createTime;
            Aim.Portal.ServicesProvider.LogService.LogEntityResponse retVal = ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).LogEntity(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Aim.Portal.ServicesProvider.LogService.LogServiceSoap.BeginLogEntity(Aim.Portal.ServicesProvider.LogService.LogEntityRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogEntity(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogEntity(string entityName, string action, string message, string userId, string userName, System.DateTime createTime, System.AsyncCallback callback, object asyncState) {
            Aim.Portal.ServicesProvider.LogService.LogEntityRequest inValue = new Aim.Portal.ServicesProvider.LogService.LogEntityRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.LogService.LogEntityRequestBody();
            inValue.Body.entityName = entityName;
            inValue.Body.action = action;
            inValue.Body.message = message;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.createTime = createTime;
            return ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).BeginLogEntity(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.LogService.LogEntityResponse Aim.Portal.ServicesProvider.LogService.LogServiceSoap.EndLogEntity(System.IAsyncResult result) {
            return base.Channel.EndLogEntity(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLogEntity(System.IAsyncResult result) {
            Aim.Portal.ServicesProvider.LogService.LogEntityResponse retVal = ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).EndLogEntity(result);
        }
        
        private System.IAsyncResult OnBeginLogEntity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string entityName = ((string)(inValues[0]));
            string action = ((string)(inValues[1]));
            string message = ((string)(inValues[2]));
            string userId = ((string)(inValues[3]));
            string userName = ((string)(inValues[4]));
            System.DateTime createTime = ((System.DateTime)(inValues[5]));
            return this.BeginLogEntity(entityName, action, message, userId, userName, createTime, callback, asyncState);
        }
        
        private object[] OnEndLogEntity(System.IAsyncResult result) {
            this.EndLogEntity(result);
            return null;
        }
        
        private void OnLogEntityCompleted(object state) {
            if ((this.LogEntityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogEntityAsync(string entityName, string action, string message, string userId, string userName, System.DateTime createTime) {
            this.LogEntityAsync(entityName, action, message, userId, userName, createTime, null);
        }
        
        public void LogEntityAsync(string entityName, string action, string message, string userId, string userName, System.DateTime createTime, object userState) {
            if ((this.onBeginLogEntityDelegate == null)) {
                this.onBeginLogEntityDelegate = new BeginOperationDelegate(this.OnBeginLogEntity);
            }
            if ((this.onEndLogEntityDelegate == null)) {
                this.onEndLogEntityDelegate = new EndOperationDelegate(this.OnEndLogEntity);
            }
            if ((this.onLogEntityCompletedDelegate == null)) {
                this.onLogEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogEntityCompleted);
            }
            base.InvokeAsync(this.onBeginLogEntityDelegate, new object[] {
                        entityName,
                        action,
                        message,
                        userId,
                        userName,
                        createTime}, this.onEndLogEntityDelegate, this.onLogEntityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.LogService.LogPropertyResponse Aim.Portal.ServicesProvider.LogService.LogServiceSoap.LogProperty(Aim.Portal.ServicesProvider.LogService.LogPropertyRequest request) {
            return base.Channel.LogProperty(request);
        }
        
        public void LogProperty(string entityName, string propertyName, string oldValue, string newValue, string userId, string userName, System.DateTime createTime) {
            Aim.Portal.ServicesProvider.LogService.LogPropertyRequest inValue = new Aim.Portal.ServicesProvider.LogService.LogPropertyRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.LogService.LogPropertyRequestBody();
            inValue.Body.entityName = entityName;
            inValue.Body.propertyName = propertyName;
            inValue.Body.oldValue = oldValue;
            inValue.Body.newValue = newValue;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.createTime = createTime;
            Aim.Portal.ServicesProvider.LogService.LogPropertyResponse retVal = ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).LogProperty(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Aim.Portal.ServicesProvider.LogService.LogServiceSoap.BeginLogProperty(Aim.Portal.ServicesProvider.LogService.LogPropertyRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogProperty(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogProperty(string entityName, string propertyName, string oldValue, string newValue, string userId, string userName, System.DateTime createTime, System.AsyncCallback callback, object asyncState) {
            Aim.Portal.ServicesProvider.LogService.LogPropertyRequest inValue = new Aim.Portal.ServicesProvider.LogService.LogPropertyRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.LogService.LogPropertyRequestBody();
            inValue.Body.entityName = entityName;
            inValue.Body.propertyName = propertyName;
            inValue.Body.oldValue = oldValue;
            inValue.Body.newValue = newValue;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.createTime = createTime;
            return ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).BeginLogProperty(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.LogService.LogPropertyResponse Aim.Portal.ServicesProvider.LogService.LogServiceSoap.EndLogProperty(System.IAsyncResult result) {
            return base.Channel.EndLogProperty(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndLogProperty(System.IAsyncResult result) {
            Aim.Portal.ServicesProvider.LogService.LogPropertyResponse retVal = ((Aim.Portal.ServicesProvider.LogService.LogServiceSoap)(this)).EndLogProperty(result);
        }
        
        private System.IAsyncResult OnBeginLogProperty(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string entityName = ((string)(inValues[0]));
            string propertyName = ((string)(inValues[1]));
            string oldValue = ((string)(inValues[2]));
            string newValue = ((string)(inValues[3]));
            string userId = ((string)(inValues[4]));
            string userName = ((string)(inValues[5]));
            System.DateTime createTime = ((System.DateTime)(inValues[6]));
            return this.BeginLogProperty(entityName, propertyName, oldValue, newValue, userId, userName, createTime, callback, asyncState);
        }
        
        private object[] OnEndLogProperty(System.IAsyncResult result) {
            this.EndLogProperty(result);
            return null;
        }
        
        private void OnLogPropertyCompleted(object state) {
            if ((this.LogPropertyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogPropertyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogPropertyAsync(string entityName, string propertyName, string oldValue, string newValue, string userId, string userName, System.DateTime createTime) {
            this.LogPropertyAsync(entityName, propertyName, oldValue, newValue, userId, userName, createTime, null);
        }
        
        public void LogPropertyAsync(string entityName, string propertyName, string oldValue, string newValue, string userId, string userName, System.DateTime createTime, object userState) {
            if ((this.onBeginLogPropertyDelegate == null)) {
                this.onBeginLogPropertyDelegate = new BeginOperationDelegate(this.OnBeginLogProperty);
            }
            if ((this.onEndLogPropertyDelegate == null)) {
                this.onEndLogPropertyDelegate = new EndOperationDelegate(this.OnEndLogProperty);
            }
            if ((this.onLogPropertyCompletedDelegate == null)) {
                this.onLogPropertyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogPropertyCompleted);
            }
            base.InvokeAsync(this.onBeginLogPropertyDelegate, new object[] {
                        entityName,
                        propertyName,
                        oldValue,
                        newValue,
                        userId,
                        userName,
                        createTime}, this.onEndLogPropertyDelegate, this.onLogPropertyCompletedDelegate, userState);
        }
    }
}
