//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oncontrol3.Web.COND801 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap")]
    public interface BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap {
        
        // CODEGEN: 消息部分命名空间 http://BizTalk.RFC.TM_CRM_801.Schemas.OUTPUT.Z2FM_COND_CREATE_RES 以后生成的消息协定与默认值(http://tempuri.org/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BizTalk_RFC_TM_CRM_801_Orchestration_Inbound/Exec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Z2FM_COND_CREATE_RES")]
        Oncontrol3.Web.COND801.ExecResponse Exec(Oncontrol3.Web.COND801.ExecRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
    public partial class Z2FM_COND_CREATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Z2FM_COND_CREATEIS_CONDITION iS_CONDITIONField;
        
        private string iV_SIMULATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Z2FM_COND_CREATEIS_CONDITION IS_CONDITION {
            get {
                return this.iS_CONDITIONField;
            }
            set {
                this.iS_CONDITIONField = value;
                this.RaisePropertyChanged("IS_CONDITION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IV_SIMULATE {
            get {
                return this.iV_SIMULATEField;
            }
            set {
                this.iV_SIMULATEField = value;
                this.RaisePropertyChanged("IV_SIMULATE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
    public partial class Z2FM_COND_CREATEIS_CONDITION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string cONDITION_IDField;
        
        private string cOND_DESCRField;
        
        private string cONDITION_TYPEField;
        
        private string cONDITION_ORIGINField;
        
        private string gENERATE_CODEField;
        
        private Z2FM_COND_CREATEIS_CONDITIONCOND_DAD[] cOND_DADField;
        
        private Z2FM_COND_CREATEIS_CONDITIONCOND_DOCU[] cOND_DOCUField;
        
        private Z2FM_COND_CREATEIS_CONDITIONCOND_DECISION[] cOND_DECISIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CONDITION_ID {
            get {
                return this.cONDITION_IDField;
            }
            set {
                this.cONDITION_IDField = value;
                this.RaisePropertyChanged("CONDITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COND_DESCR {
            get {
                return this.cOND_DESCRField;
            }
            set {
                this.cOND_DESCRField = value;
                this.RaisePropertyChanged("COND_DESCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CONDITION_TYPE {
            get {
                return this.cONDITION_TYPEField;
            }
            set {
                this.cONDITION_TYPEField = value;
                this.RaisePropertyChanged("CONDITION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CONDITION_ORIGIN {
            get {
                return this.cONDITION_ORIGINField;
            }
            set {
                this.cONDITION_ORIGINField = value;
                this.RaisePropertyChanged("CONDITION_ORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GENERATE_CODE {
            get {
                return this.gENERATE_CODEField;
            }
            set {
                this.gENERATE_CODEField = value;
                this.RaisePropertyChanged("GENERATE_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COND_DAD", Order=6)]
        public Z2FM_COND_CREATEIS_CONDITIONCOND_DAD[] COND_DAD {
            get {
                return this.cOND_DADField;
            }
            set {
                this.cOND_DADField = value;
                this.RaisePropertyChanged("COND_DAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COND_DOCU", Order=7)]
        public Z2FM_COND_CREATEIS_CONDITIONCOND_DOCU[] COND_DOCU {
            get {
                return this.cOND_DOCUField;
            }
            set {
                this.cOND_DOCUField = value;
                this.RaisePropertyChanged("COND_DOCU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COND_DECISION", Order=8)]
        public Z2FM_COND_CREATEIS_CONDITIONCOND_DECISION[] COND_DECISION {
            get {
                return this.cOND_DECISIONField;
            }
            set {
                this.cOND_DECISIONField = value;
                this.RaisePropertyChanged("COND_DECISION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
    public partial class Z2FM_COND_CREATEIS_CONDITIONCOND_DAD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string dADField;
        
        private string dOBJ_DESCRIPTIONField;
        
        private string dEC_TAB_POSField;
        
        private string iNPUT_REQUIREDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DAD {
            get {
                return this.dADField;
            }
            set {
                this.dADField = value;
                this.RaisePropertyChanged("DAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DOBJ_DESCRIPTION {
            get {
                return this.dOBJ_DESCRIPTIONField;
            }
            set {
                this.dOBJ_DESCRIPTIONField = value;
                this.RaisePropertyChanged("DOBJ_DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DEC_TAB_POS {
            get {
                return this.dEC_TAB_POSField;
            }
            set {
                this.dEC_TAB_POSField = value;
                this.RaisePropertyChanged("DEC_TAB_POS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string INPUT_REQUIRED {
            get {
                return this.iNPUT_REQUIREDField;
            }
            set {
                this.iNPUT_REQUIREDField = value;
                this.RaisePropertyChanged("INPUT_REQUIRED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
    public partial class Z2FM_COND_CREATEIS_CONDITIONCOND_DOCU : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string lANGUField;
        
        private string dOCUMENTATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LANGU {
            get {
                return this.lANGUField;
            }
            set {
                this.lANGUField = value;
                this.RaisePropertyChanged("LANGU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DOCUMENTATION {
            get {
                return this.dOCUMENTATIONField;
            }
            set {
                this.dOCUMENTATIONField = value;
                this.RaisePropertyChanged("DOCUMENTATION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
    public partial class Z2FM_COND_CREATEIS_CONDITIONCOND_DECISION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cOND_KEYField;
        
        private string cOL_NOField;
        
        private string rOW_NOField;
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string r_LOW_VALUEField;
        
        private string r_HIGH_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] COND_KEY {
            get {
                return this.cOND_KEYField;
            }
            set {
                this.cOND_KEYField = value;
                this.RaisePropertyChanged("COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COL_NO {
            get {
                return this.cOL_NOField;
            }
            set {
                this.cOL_NOField = value;
                this.RaisePropertyChanged("COL_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ROW_NO {
            get {
                return this.rOW_NOField;
            }
            set {
                this.rOW_NOField = value;
                this.RaisePropertyChanged("ROW_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SIGN {
            get {
                return this.sIGNField;
            }
            set {
                this.sIGNField = value;
                this.RaisePropertyChanged("SIGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OPTION {
            get {
                return this.oPTIONField;
            }
            set {
                this.oPTIONField = value;
                this.RaisePropertyChanged("OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string R_LOW_VALUE {
            get {
                return this.r_LOW_VALUEField;
            }
            set {
                this.r_LOW_VALUEField = value;
                this.RaisePropertyChanged("R_LOW_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string R_HIGH_VALUE {
            get {
                return this.r_HIGH_VALUEField;
            }
            set {
                this.r_HIGH_VALUEField = value;
                this.RaisePropertyChanged("R_HIGH_VALUE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.OUTPUT.Z2FM_COND_CREATE_RES")]
    public partial class Z2FM_COND_CREATE_RES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eV_COND_KEYField;
        
        private Z2FM_COND_CREATE_RESET_MESSAGE[] eT_MESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EV_COND_KEY {
            get {
                return this.eV_COND_KEYField;
            }
            set {
                this.eV_COND_KEYField = value;
                this.RaisePropertyChanged("EV_COND_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ET_MESSAGE", Order=1)]
        public Z2FM_COND_CREATE_RESET_MESSAGE[] ET_MESSAGE {
            get {
                return this.eT_MESSAGEField;
            }
            set {
                this.eT_MESSAGEField = value;
                this.RaisePropertyChanged("ET_MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.OUTPUT.Z2FM_COND_CREATE_RES")]
    public partial class Z2FM_COND_CREATE_RESET_MESSAGE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Exec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.INPUT.Z2FM_COND_CREATE")]
        public Oncontrol3.Web.COND801.Z2FM_COND_CREATE Z2FM_COND_CREATE;
        
        public ExecRequest() {
        }
        
        public ExecRequest(Oncontrol3.Web.COND801.Z2FM_COND_CREATE Z2FM_COND_CREATE) {
            this.Z2FM_COND_CREATE = Z2FM_COND_CREATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.OUTPUT.Z2FM_COND_CREATE_RES", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk.RFC.TM_CRM_801.Schemas.OUTPUT.Z2FM_COND_CREATE_RES")]
        public Oncontrol3.Web.COND801.Z2FM_COND_CREATE_RES Z2FM_COND_CREATE_RES;
        
        public ExecResponse() {
        }
        
        public ExecResponse(Oncontrol3.Web.COND801.Z2FM_COND_CREATE_RES Z2FM_COND_CREATE_RES) {
            this.Z2FM_COND_CREATE_RES = Z2FM_COND_CREATE_RES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapChannel : Oncontrol3.Web.COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient : System.ServiceModel.ClientBase<Oncontrol3.Web.COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap>, Oncontrol3.Web.COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap {
        
        public BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient() {
        }
        
        public BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Oncontrol3.Web.COND801.ExecResponse Oncontrol3.Web.COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap.Exec(Oncontrol3.Web.COND801.ExecRequest request) {
            return base.Channel.Exec(request);
        }
        
        public Oncontrol3.Web.COND801.Z2FM_COND_CREATE_RES Exec(Oncontrol3.Web.COND801.Z2FM_COND_CREATE Z2FM_COND_CREATE) {
            Oncontrol3.Web.COND801.ExecRequest inValue = new Oncontrol3.Web.COND801.ExecRequest();
            inValue.Z2FM_COND_CREATE = Z2FM_COND_CREATE;
            Oncontrol3.Web.COND801.ExecResponse retVal = ((Oncontrol3.Web.COND801.BizTalk_RFC_TM_CRM_801_Orchestration_InboundSoap)(this)).Exec(inValue);
            return retVal.Z2FM_COND_CREATE_RES;
        }
    }
}
